### ISSUE TITLE
Audinarey - Users can DOS withdrawal processing if they get blacklisted after

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-mellow-judging#109]
Audinarey

Medium

# Users can DOS withdrawal processing if they get blacklisted after

## Summary
Per the changes made duriing the course of the audit on discord announced by @wang [here](https://discord.com/channels/812037309376495636/1252276613417013353/1254895536629219428) and confirmed by @armoking32 [here](https://discord.com/channels/812037309376495636/1252276613417013353/1254895536629219428) that the protocols whitelisted tokens now include USDT and USDC.

If a user specifies an address that has been blacklisted by USDC as the recipient of a withdrawal request, the `processWithdrawals(...)` function will revert.

## Vulnerability Detail

`processWithdrawals(...)` is used to process withdrawals for an array of users and the expected amount of each user who has requested a withdrawal will be sent the address (`request.to`) specified by the user who made the request. However, if the specified recipient has been blacklisted by USDC, the `processWithdrawals(...)` function will revert blocking withdrawals for other users

```solidity
File: Vault.sol
538:     /// @inheritdoc IVault
539:     function processWithdrawals(
540:         address[] memory users
541:     ) external nonReentrant returns (bool[] memory statuses) {
SNIP
......
562: 
563:             for (uint256 j = 0; j < s.tokens.length; j++) {
564:                 s.erc20Balances[j] -= expectedAmounts[j];
565:                 IERC20(s.tokens[j]).safeTransfer(
566:                     request.to,
567:    @>               expectedAmounts[j]
568:                 );
569:             }
SNIP
.......
584:         emit WithdrawCallback(callback);
585:     }

```

## Impact
This can lead to a Denial of Service for users when redeeming their lp token for their underlying asset

## Code Snippet
https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L461-L468

## Tool used
Manual Review

## Recommendation
Modify the `processWithdrawals(...)` function to use a `try/catch` as shown below

```solidity

File: Vault.sol

538:     /// @inheritdoc IVault
539:     function processWithdrawals(
540:         address[] memory users
541:     ) external nonReentrant returns (bool[] memory statuses) {
SNIP
......
562: 

563:  -           for (uint256 j = 0; j < s.tokens.length; j++) {
564:  -               s.erc20Balances[j] -= expectedAmounts[j];
565:  -               IERC20(s.tokens[j]).safeTransfer(
566:  -                   request.to,
567:  -                   expectedAmounts[j]
568:  -               );
569:  -           }

563:  +           for (uint256 j = 0; j < s.tokens.length; j++) {
564:  +               s.erc20Balances[j] -= expectedAmounts[j];
565:  +               try IERC20(s.tokens[j]).safeTransfer(
566:  +                   request.to,
567:  +                   expectedAmounts[j]
568:  +               ) {} catch { continue }
569:  +           }

SNIP
.......
584:         emit WithdrawCallback(callback);
585:     }
```

**Comment by 10xhash** [comment]
> Invalid; The Operator can use `processWithdrawals()` and ignore the blacklisted users.

Escalate

Ignoring blacklisted user's off-chain before the call will not work as user's are able to update their withdrawal request. Hence a user can keep a non-blacklisted address in the initial request and then front-run the admin's processWithdrawals call (which includes the attacker's withdrawal request because the `to` param is non-blacklisted) and change the `to` param to a blacklisted user

**Comment by sherlock-admin3** [comment]
> > Invalid; The Operator can use `processWithdrawals()` and ignore the blacklisted users.
> 
> Escalate
> 
> Ignoring blacklisted user's off-chain before the call will not work as user's are able to update their withdrawal request. Hence a user can keep a non-blacklisted address in the initial request and then front-run the admin's processWithdrawals call (which includes the attacker's withdrawal request because the `to` param is non-blacklisted) and change the `to` param to a blacklisted user

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by z3s** [comment]
> front-run

The front-run scenario, wasn't mentioned in the original submission.
Protocol team comment about front-run issues:
> processWithdrawals will occur through flashbots.

**Comment by Audinarey** [comment]
@z3s  The use of flashbots or even kepeers was not mentioned in the audit QA

**Comment by Audinarey** [comment]
<img width="704" alt="Screenshot 2024-07-17 at 09 46 00" src="https://github.com/user-attachments/assets/5140e6fa-3aaf-49ab-8f6f-6a5e009b8517">


**Are there any off-chain mechanisms or off-chain procedures for the protocol (keeper bots, arbitrage bots, etc.)?**

No.

**Comment by Audinarey** [comment]
> > front-run
> 
> The front-run scenario, wasn't mentioned in the original submission. Protocol team comment about front-run issues:
> 
> > processWithdrawals will occur through flashbots.

![image](https://github.com/user-attachments/assets/66383f3b-63ab-445c-ba9d-573eb788f855)

**Are there any off-chain mechanisms or off-chain procedures for the protocol (keeper bots, arbitrage bots, etc.)?**

No.

**Comment by Audinarey** [comment]
The [rules for this contest](https://github.com/sherlock-protocol/sherlock-v2-docs/blob/29a019b8690eb01df3587868c4d7eac1e3459bda/audits/judging/judging/README.md#iii-sherlocks-standards) states

> If the protocol **team provides specific information in the README** or CODE COMMENTS, **that information stands above all judging rules**. In case of contradictions between the README and CODE COMMENTS, the README is the chosen source of truth.

**Comment by 0xHuntoor** [comment]
i may be biased but this may have two faces

1. Valid cause any and always delaying normal withdrawal processing -> forcing them to `emergencyWithdraw` and accepting loss as stated in readMe (time sensitive function)
2. invalid due to  the lovely 1 block dos in Sherlock Docs.

**Comment by Audinarey** [comment]
@IlIlHunterlIlI 

> 2. invalid due to the lovely 1 block dos in Sherlock Docs.

I assume you brought this up becuase @10xhash mentioned a second attack path (frontrunning the .....)

> ... is considered _a DoS of a single block_, hence only *if the function is clearly time-sensitive*, it can be a Medium severity issue..


The `processWithdrawals(...)` function is a time sensitive function, because it calls [`analyzeRequest(...)`](https://github.com/sherlock-audit/2024-06-mellow/blob/26aa0445ec405a4ad637bddeeedec4efe1eba8d2/mellow-lrt/src/Vault.sol#L481-L483) to ensure that only request that have not exceeded their deadline at the point the `ProcessWithdrawalsStack` is evaluated are processed successfully.

**Comment by 0xHuntoor** [comment]
Sir, i have same issue as dup. Just giving useful insights for the HoJ

**Comment by Audinarey** [comment]
> Sir, i have same issue as dup. Just giving useful insights for the HoJ

@IlIlHunterlIlI 

Then you should take down your comment and desist from dropping insights that would make this longer than it should be by giving HOJ insights to invalidate your finding and wait for him to do his work.

As a matter of fact if you are biased about your finding then you should ask the judge to dedupp it from this finding and give more reasons why yours is not valid

**Comment by 0xHuntoor** [comment]
I truly think people in this contest should relax.

What i did is shortening the duration of this escalation by packing the possibilities. My comments never determine the validation

**Comment by IWildSniperI** [comment]
i see this in the readMe 
> Are there any off-chain mechanisms or off-chain procedures for the protocol (keeper bots, arbitrage bots, etc.)?
No.

aren't excluding the blacklisted user considered to be off-chain procedure?

**Comment by WangSecurity** [comment]
@Audinarey please be more respectful.

I've hidden several comments, cause they're either duplicates of other or off-topic and don't bring any value.

I agree with the lead judge that the scenario of front-running wasn't mentioned in the report. The report lacks sufficient proof the issue could still happen if the operator ignored the blacklisted users as shared by the LSW [here](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/109#issuecomment-2231629207). 

Thus, this report is not sufficient to be valid, but I'll check the duplicates to see if there are any valid ones and will accept escalation if there are indeed any.

**Comment by xKeywordx** [comment]
@WangSecurity this can also be DoS'ed in the case of native ETH. If the depositor is a contract address that has a receive function that will always revert, when the token being transferred is native ETH, this will also DoS the withdrawals for all other users. My issue, finding #207  explains this.

**Comment by WangSecurity** [comment]
About #207, the user can deposit ETH in the contract, but it will be stored as wstETH in the vault (DepositWrapper), and as I understand the users cannot withdraw ETH, since it's not payable and doesn't transfer any `msg.value`.

About this report, the decision is that the `processWithdrawals` function is not time-sensitive. Hence, I believe at most the DOS is for one block, then the Operator can ignore any requests with blacklisted addresses. Even in case in the escalation comment, it's still a DOS for one block, even though can be repeated perpetually.

The decision is to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [10xhash](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/109/#issuecomment-2231629207): rejected
