### ISSUE TITLE
infect3d - `!isProcessingPossible` case inside `processWithdrawals` canceling user withdrawal request can cause issues

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-mellow-judging#121]
infect3d

Medium

# `!isProcessingPossible` case inside `processWithdrawals` canceling user withdrawal request can cause issues

## Summary
External factor like vault state and price variation can cause a user withdrawal request to be canceled if his request is processed at the same time, forcing him to create a new request, resetting his emergency withdrawal request timer to zero.

## Vulnerability Detail
User who have deposited into a vault can chose to withdraw their assets and the earned yield by calling `registerWithdrawal`, which will create add their request to a withdrawal queue. The withdrawal request can then be processed either by an Operator through `processWithdrawals`, or through `emergencyWithdrawal` by the user who created the request once the `emergencyWithdrawalDelay` has passed.

When registering a withdrawal, the user can set `request.minAmounts` the minimum of amount of asset he expect to get through the process. **This amount will depend then of the state of the vault and the price of the assets at the time the withdrawal is processed**, by the computation of the `ratioX96Value`.

During `processWithdrawals`, `analyzeRequest` will compare `expectedAmounts` (the amount that will be sent to user) to `request.minAmounts`, and will return `isProcessingPossible = false` when `expectedAmounts > request.minAmounts`

The issue here is that when this happens, the user request is [automatically canceled](https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L554-L554), which simply delete the request from the queue, meaning user will have to create a fresh new request.
Because the user will have to create a new request, all the time that has passed since creation, and would have allowed him to call `emergencyWithdraw` himself, will be reset to 0 without his consent or his knowledge.
The user will then have to go through the whole delay once again, and will still risk the same event as the vault state and asset price cannot be predicted.

## Impact
User can see their right to call `emergencyWithdraw` reset to zero because of fluctuating prices and vault state which is out of their control. 
Because the timer is reset, they might be subject to unfair risk event that could have been avoided if the timer was not reset on their behalf.

## Code Snippet

https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L554-L554
```solidity
File: src/Vault.sol
536:     function processWithdrawals(
537:         address[] memory users
538:     ) external nonReentrant returns (bool[] memory statuses) {
539:         _requireAtLeastOperator();
540:         statuses = new bool[](users.length);
541:         ProcessWithdrawalsStack memory s = calculateStack();
542:         uint256 burningSupply = 0;
543:         for (uint256 i = 0; i < users.length; i++) {
544:             address user = users[i];
545:             if (!_pendingWithdrawers.contains(user)) continue;
546:             WithdrawalRequest memory request = _withdrawalRequest[user];
547:             (
548:                 bool isProcessingPossible,
549:                 bool isWithdrawalPossible,
550:                 uint256[] memory expectedAmounts
551:             ) = analyzeRequest(s, request);
552: 
553:             if (!isProcessingPossible) {
554:⚠				 _cancelWithdrawalRequest(user);
555:				 continue;
556:             }
```

## Tool used
Manual review

## Recommendation
Do not cancel the withdrawal request when `isProcessingPossible = false`
It may be better to make the request cancelable by the operator based on its age.

**Comment by InfectedIsm** [comment]
Escalate

This report shows how **a core contract functionality** can be unexpectedly broken by using the protocol as expected: i.e, user being able to call emergencyWithdraw after`emergencyWithdrawalDelay` has passed.
Even if the operator and the user are honest, the issue can happen and user will lose his right to make an emergency withdrawal.

For this reason this issue should be considered medium.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This report shows how **a core contract functionality** can be unexpectedly broken by using the protocol as expected: i.e, user being able to call emergencyWithdraw after`emergencyWithdrawalDelay` has passed.
> Even if the operator and the user are honest, the issue can happen and user will lose his right to make an emergency withdrawal.
> 
> For this reason this issue should be considered medium.

You've deleted an escalation for this issue.

**Comment by z3s** [comment]
I think it's a design decision, and users usually set tight slippage controls when the handling of withdrawals works normally.
> Design decisions are not valid issues. Even if the design is suboptimal, but doesn't imply any loss of funds, these issues are considered informational.

**Comment by InfectedIsm** [comment]
@z3s I get your point of view and this make sense.

However, the idea of loss of funds cannot be ignored, as LST are subject to slashing events. 

By deposit their assets into the vault, users transfer their trust to the protocol (and operator). 

But as shown in the submission, even if the operator take all precautions to send the `processWithdrawals`  tx only when all conditions are met, a price update transaction can still be placed earlier in the block regardless, causing the issue described.

If significant price movement happens within the same block as a withdrawal, user will have its timer reset and be exposed for more time than it has signed for.
Then, during this time users will be exposed to the risk of slashing, potentially causing a loss of funds.

Deployed value for `emergencyWithdrawalDelay` are 7776000 (or 90 days) (e.g : [Configurator contract](https://etherscan.io/address/0xe6180599432767081beA7deB76057Ce5883e73Be#readContract)).
Given such an extended period, the potential impact for the user, as much as the likelihood of this happening isn't negligible.

**Comment by 0xklapouchy** [comment]
@z3s 

This is a slippage protection mechanism and is working as expected.

If not configured this way, a user could set minAmount to extreme values that will never be processed, forcing the protocol to allow emergencyWithdrawal(), which is a last resort in the Mellow protocol and should be avoided at any cost.

**Comment by InfectedIsm** [comment]
@0xklapouchy you are right, I did not notice that `EmergencyWithdrawal` do not incur fees on withdrawal compared to a standard withdrawal, which is detrimental to the protocol.
While the current handling of the situation still doesn't seem right, I must admit there's no perfect solution here, just design improvements as mentioned by @z3s.
Therefore, I will cancel my escalation.
Thanks for this valuable conversation both of you, really appreciate.
Cheers
