### ISSUE TITLE
HexaSecure - missing `receive()` function to receive unwrapped ETH in stakingModule.sol

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-mellow-judging#132]
HexaSecure

Medium

# missing `receive()` function to receive unwrapped ETH in stakingModule.sol

## Summary
stakingModule.sol won't be able to receive unwrapped ETH due to missing receive() function.

## Vulnerability Detail
```solidity
    function _wethToWSteth(uint256 amount) private {
        IWeth(weth).withdraw(amount);// @audit-issue missing payable function to receive unwrapped ETH. 
        
        ISteth(steth).submit{value: amount}(address(0));
        IERC20(steth).safeIncreaseAllowance(address(wsteth), amount);
        IWSteth(wsteth).wrap(amount);
    }
```

In `stakingModule._wethToWSteth()`, weth.withdraw() is called to unwrap ETH. 

The issue here is that due to the `stakingModule` contract lacking the receive function, there will be reverts.

## Impact
The missing `receive()` function makes the contract unable to receive unwrapped ETH.

## Code Snippet
https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/modules/obol/StakingModule.sol#L78
## Tool used

Manual Review

## Recommendation

add the receive() function to stakingModule.sol

**Comment by Dliteofficial** [comment]
@armoking32 @WangSecurity we didn't get any reason for the sponsor's dispute

**Comment by armoking32** [comment]
> @armoking32 @WangSecurity we didn't get any reason for the sponsor's dispute

This is a completely invalid issue. StakingModule is a delegate Module, and the corresponding receive function is in the Vault.sol code itself.
