### ISSUE TITLE
den_sosnovskyi - Not correct underlyingAmount in `DefaultBondTvlModule` contract

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-mellow-judging#147]
den_sosnovskyi

Medium

# Not correct underlyingAmount in `DefaultBondTvlModule` contract

## Summary
Data struct in `DefaultBondTvlModule` has not correct underlyingAmount. It can be manipualated by the attacker

## Vulnerability Detail
In the `DefaultBondTvlModule::tvl` we count total value locked for two different tokens: token = `bonds[i]`, and underlyingToken = `IBond(bonds[i]).asset()`. Even though those tokens seems to have 1:1 ratio, we count token amount as `IERC20(bonds[i]).balanceOf(vault)`, and underlyingToken amount as `data[i].amount`. This implies that token amount and underlyingToken amount will always be the same. But because we use ERC20 `balanceOf` function to count the amount, attacker can send either `token` or `underlyingToken` to the vault, so that the ratio of total locked amounts will no be 1:1 anymore

## Impact
Will not count real total value locked correctly

## Code Snippet
https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/modules/symbiotic/DefaultBondTvlModule.sol#L32-L37

## Tool used

Manual Review

## Recommendation
Use instead of `data[i].underlyingAmount = data[i].amount` - `data[i].underlyingAmount = IERC20(bonds[i].asset()).balanceOf(vault)`

Duplicate of #164

**Comment by recursiveEth** [comment]
Escalate 
this is duplicate of #164, Impact of the above issue, while calculating the _calculateTvl function which calculate the total value locked using _tvl function which gives amount locked in Modules, it has a bool variable which shows whether that token is underlying or not if yes it will give underlying token and its amount, otherwise base token and its amount.
in above issue token address is assigned properly but its amount values are not assigned properly so whether bool is true or false
_CalculateTvl return same amount, which represents the wrong accounting. Thank you

**Comment by sherlock-admin3** [comment]
> Escalate 
> this is duplicate of #164, Impact of the above issue, while calculating the _calculateTvl function which calculate the total value locked using _tvl function which gives amount locked in Modules, it has a bool variable which shows whether that token is underlying or not if yes it will give underlying token and its amount, otherwise base token and its amount.
> in above issue token address is assigned properly but its amount values are not assigned properly so whether bool is true or false
> _CalculateTvl return same amount, which represents the wrong accounting. Thank you
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Planning to reject the escalation and leave the issue as it is based on the very same decision as [here](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/164#issuecomment-2236172709)

**Comment by WangSecurity** [comment]
Result:
Invalid
Duplicate of #164

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [recursiveEth](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/147/#issuecomment-2231083802): rejected
