### ISSUE TITLE
den_sosnovskyi - `SimpleDVTStakingStrategy::processWithdrawals` does not check low level delegateCall response

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-mellow-judging#148]
den_sosnovskyi

Medium

# `SimpleDVTStakingStrategy::processWithdrawals` does not check low level delegateCall response

## Summary
`SimpleDVTStakingStrategy::processWithdrawals` does not check delegateCall response which will not revert in case of low level delegate call error.

## Vulnerability Detail
`SimpleDVTStakingStrategy::processWithdrawals` calls `vault.delegateCall` function. This calls low level `to.delegatecall(data)` function. It retuns success boolean instead of revert. The protocol does not check if is false neither in the Vault contract, nor in the SimpleDVTStakingStrategy contract. It means in case delegate call fails, `statuses = vault.processWithdrawals(users);` inside of `SimpleDVTStakingStrategy::processWithdrawals` will be still executed

## Impact
Can lead to unexpected functioning inside `SimpleDVTStakingStrategy::processWithdrawals` function

## Code Snippet
https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/strategies/SimpleDVTStakingStrategy.sol#L72-L83
https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L280-L282

## Tool used

Manual Review

## Recommendation

Add check if success variable is false, than revert

**Comment by recursiveEth** [comment]
Escalate
issue number is #148, the issue is not regarding the events which is emitted upon successful call or not, its about reverting when the low level call delegate call didn't not successful makes the transaction as they won't revert by there own due to low-level functionality they are not similar as require methods

**Comment by sherlock-admin3** [comment]
> Escalate
> issue number is #148, the issue is not regarding the events which is emitted upon successful call or not, its about reverting when the low level call delegate call didn't not successful makes the transaction as they won't revert by there own due to low-level functionality they are not similar as require methods

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by z3s** [comment]
#169

**Comment by WangSecurity** [comment]
In this case it's up to the caller to decide if they want to check the success of the call or not, since the success boolean is returned in the function and emitted in the event.

Planning to reject both escalations and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [recursiveEth](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/148/#issuecomment-2231101099): rejected
