### ISSUE TITLE
den_sosnovskyi - `ChainlinkOracle` contract allows admin to add adress(0) aggregator which will lead to the block of `getPrice`  function

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-mellow-judging#149]
den_sosnovskyi

Medium

# `ChainlinkOracle` contract allows admin to add adress(0) aggregator which will lead to the block of `getPrice`  function

## Summary
`ChainlinkOracle::setChainlinkOracles` check whether data_[i].aggregatorV3 == address(0) to skip validation, but still adds it to the _aggregatorsData mapping

## Vulnerability Detail
Admin can add Chainlink address(0) aggregator. Even though the check is present here for this case, it skips validation but still allows admin to add the broken aggregator to the `_aggregatorsData` mapping. When user calls `getPrice` function, it can revert due to calling address(0) as a chainlink aggreagator

## Impact
Can temporary block the price fetching functionality

## Code Snippet
https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/oracles/ChainlinkOracle.sol#L41-L47

## Tool used

Manual Review

## Recommendation

Skip adding address(0) to the `_aggregatorsData` mapping

**Comment by recursiveEth** [comment]
Escalate
 it's a issue because it iterates over the tokens array, skipping entries where data_[i].aggregatorV3 is address(0) and validating the rest, check the vulnerability details again.
Even though it's a admin function there is mistake in code, they have prior check for zero aggregator address which means they have additional check and adding the same address 0 in next statement is code mistake as there the whole segment of code dedicated to handling such paths it doesn't depend of admin please have a look carefully, thank you

**Comment by sherlock-admin3** [comment]
> Escalate
>  it's a issue because it iterates over the tokens array, skipping entries where data_[i].aggregatorV3 is address(0) and validating the rest, check the vulnerability details again.
> Even though it's a admin function there is mistake in code, they have prior check for zero aggregator address which means they have additional check and adding the same address 0 in next statement is code mistake as there the whole segment of code dedicated to handling such paths it doesn't depend of admin please have a look carefully, thank you

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by z3s** [comment]
#173

**Comment by WangSecurity** [comment]
I see it's a duplicate of #245, but I believe it's not sufficient. The report talks about `getPrice` returning false value, but as I see it's a public view function. Hence the following rule applies:
> Incorrect values in View functions are by default considered low

Planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [recursiveEth](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/149/#issuecomment-2231126084): rejected
