### ISSUE TITLE
recursiveEth - Potential Silent Failure in `delegateCall` Function Due to Unchecked Delegate Call Result

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-mellow-judging#165]
recursiveEth

Medium

# Potential Silent Failure in `delegateCall` Function Due to Unchecked Delegate Call Result

## Summary
The `delegateCall` function allows for the execution of a low-level delegate call to a specified address. However, delegate calls are known to return false rather than reverting when they fail. This can lead to silent failures, which can have significant implications if this function is used to delegate calls to critical modules such as the bond module for token deposits. The function currently emits an event with the success status but does not handle the case where the delegate call fails, potentially leaving the system in an inconsistent state.

## Vulnerability Detail
The vulnerability arises from the use of the delegatecall low-level function. Delegate calls are inherently risky because they do not revert on failure; instead, they return false. If the delegate call fails due to gas exhaustion, invalid opcode, or other reasons, the delegateCall function will simply emit an event indicating the failure without reverting the transaction. This can lead to several issues, particularly when the delegateCall function is used to perform critical operations like token deposits in the bond module.

## Impact
Silent Failures: Delegate calls that fail will not revert the transaction, leading to silent failures. This can mask underlying issues and make debugging difficult.
Inconsistent State: Operations that rely on successful delegate calls may proceed with incorrect assumptions, resulting in an inconsistent state.
Security Risks: Critical operations such as token deposits in the bond module may not execute as expected, leading to potential security vulnerabilities and financial losses.
## Code Snippet
https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L267

```solidity 
    function delegateCall(
        address to,
        bytes calldata data
    ) external returns (bool success, bytes memory response) {
        _requireAtLeastOperator();
        if (!configurator.isDelegateModuleApproved(to)) revert Forbidden();
        IValidator validator = IValidator(configurator.validator());
        validator.validate(
            msg.sender,
            address(this),
            abi.encodeWithSelector(msg.sig, to, data)
        );
        validator.validate(address(this), to, data);
        (success, response) = to.delegatecall(data);
        emit DelegateCall(to, data, success, response);
    }
```
## Tool used

Manual Review

## Recommendation
 the `delegateCall` function should include a check for the success of the delegate call and revert if it fails

```diff 
function delegateCall(
    address to,
    bytes calldata data
) external returns (bool success, bytes memory response) {
    _requireAtLeastOperator();
    if (!configurator.isDelegateModuleApproved(to)) revert Forbidden();
    IValidator validator = IValidator(configurator.validator());
    validator.validate(
        msg.sender,
        address(this),
        abi.encodeWithSelector(msg.sig, to, data)
    );
    validator.validate(address(this), to, data);
    (success, response) = to.delegatecall(data);
+    require(success, "Delegate call failed");
    emit DelegateCall(to, data, success, response);
}

```

Duplicate of #93

**Comment by recursiveEth** [comment]
Escalate
issue number is #165, the issue is not regarding the events which is emitted upon successful call or not, its about reverting when the low level call delegate call didn't not successful makes the transaction as they won't revert by there own due to low-level functionality they are not similar as require methods, thank you

**Comment by sherlock-admin3** [comment]
> Escalate
> issue number is #165, the issue is not regarding the events which is emitted upon successful call or not, its about reverting when the low level call delegate call didn't not successful makes the transaction as they won't revert by there own due to low-level functionality they are not similar as require methods, thank you

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by z3s** [comment]
#169

**Comment by WangSecurity** [comment]
In this case it's up to the caller to decide if they want to check the success of the call or not, since the success boolean is returned in the function and emitted in the event.

Planning to reject both escalations and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Duplicate of #93

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [recursiveEth](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/165/#issuecomment-2231100725): rejected
