### ISSUE TITLE
recursiveEth - Potential Silent Failure in `externalCall` Function Due to Unchecked Call Result

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-mellow-judging#169]
recursiveEth

Medium

# Potential Silent Failure in `externalCall` Function Due to Unchecked Call Result

## Summary
The externalCall function performs an external call to a specified address using the provided calldata. However, the issues is external calls using the call method return false rather than reverting when they fail. This can lead to silent failures, leaving the system in an inconsistent state. The function currently emits an event with the success status but does not handle the case where the external call fails, which can mask underlying issues
## Vulnerability Detail
The vulnerability arises from the use of the call low-level function. External calls are risky because they do not revert on failure; instead, they return false. If the external call fails due to gas exhaustion, invalid opcode, or other reasons, the externalCall function will simply emit an event indicating the failure without reverting the transaction. This can lead to issues, especially if the external call is critical to the system's operations.
## Impact
Silent Failures: External calls that fail will not revert the transaction, leading to silent failures. This can mask underlying issues and make debugging difficult.
Inconsistent State: Operations that rely on successful external calls may proceed with incorrect assumptions, resulting in an inconsistent state.
Security Risks: Critical operations may not execute as expected, leading to potential security vulnerabilities.
## Code Snippet
https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L249

```solidity
   function externalCall(
        address to,
        bytes calldata data
    ) external nonReentrant returns (bool success, bytes memory response) {
        _requireAtLeastOperator();
        if (configurator.isDelegateModuleApproved(to)) revert Forbidden();
        IValidator validator = IValidator(configurator.validator());
        validator.validate(
            msg.sender,
            address(this),
            abi.encodeWithSelector(msg.sig, to, data)
        );
        validator.validate(address(this), to, data);
        (success, response) = to.call(data);
        emit ExternalCall(to, data, success, response);
    }
```

## Tool used

Manual Review

## Recommendation
the `externalCall` function should include a check for the success of the call and revert if it fails. 

```diff
function externalCall(
    address to,
    bytes calldata data
) external nonReentrant returns (bool success, bytes memory response) {
    _requireAtLeastOperator();
    if (configurator.isDelegateModuleApproved(to)) revert Forbidden();
    IValidator validator = IValidator(configurator.validator());
    validator.validate(
        msg.sender,
        address(this),
        abi.encodeWithSelector(msg.sig, to, data)
    );
    validator.validate(address(this), to, data);
    (success, response) = to.call(data);
+    require(success, "External call failed");
    emit ExternalCall(to, data, success, response);
}
```

Duplicate of #93

**Comment by recursiveEth** [comment]
Escalate
issue number is #169, the issue is not regarding the events which is emitted upon successful call or not, its about reverting when the low level call delegate call didn't not successful makes the transaction as they won't revert by there own due to low-level functionality they are not similar as require methods

**Comment by sherlock-admin3** [comment]
> Escalate
> issue number is #169, the issue is not regarding the events which is emitted upon successful call or not, its about reverting when the low level call delegate call didn't not successful makes the transaction as they won't revert by there own due to low-level functionality they are not similar as require methods

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by z3s** [comment]
Isn't this the design decision!?
I think Operators checks success status from emitted Events.

**Comment by recursiveEth** [comment]
Escalate
@z3s events are for the handling front-end part what about the user who directly if they have deposited into the system and there amount didn't get deposited into the modules and reverting in that case that's the issue.

**Comment by sherlock-admin3** [comment]
> Escalate
> @z3s events are for the handling front-end part what about the user who directly if they have deposited into the system and there amount didn't get deposited into the modules and reverting in that case that's the issue.
> 
>  

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
In this case it's up to the caller to decide if they want to check the success of the call or not, since the success boolean is returned in the function and emitted in the event.

Planning to reject both escalations and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Duplicate of #93

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [recursiveEth](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/169/#issuecomment-2231104570): rejected
- [recursiveEth](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/169/#issuecomment-2231211763): rejected
