### ISSUE TITLE
recursiveEth - Potential Addition of Invalid Aggregator Entries in setChainlinkOracles Function

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-mellow-judging#173]
recursiveEth

High

# Potential Addition of Invalid Aggregator Entries in setChainlinkOracles Function

## Summary
The `setChainlinkOracles` function updates `Chainlink` oracle data for a vault by setting token-to-aggregator mappings. However, the function currently allows entries with aggregatorV3 set to address(0) to be added to the _aggregatorsData mapping. This occurs because the validation loop skips these entries without validating them, while the subsequent loop adds all entries, including those with aggregatorV3 set to address(0). This discrepancy can lead to the addition of invalid or undesired entries in the _aggregatorsData mapping.
## Vulnerability Detail
The vulnerability arises from the inconsistency between the validation and mapping update logic in the setChainlinkOracles function. The function performs the following steps:

Validation Loop: It iterates over the tokens array, skipping entries where data_[i].aggregatorV3 is address(0) and validating the rest.

```solidity
for (uint256 i = 0; i < tokens.length; i++) {
    if (data_[i].aggregatorV3 == address(0)) continue;
    _validateAndGetPrice(data_[i]);
}
```
Mapping Update Loop: It iterates over the tokens array again, adding all entries to the _aggregatorsData mapping, including those with aggregatorV3 set to address(0).
```solidity 
for (uint256 i = 0; i < tokens.length; i++) {
    _aggregatorsData[vault][tokens[i]] = data_[i];
}

```
This means that entries with aggregatorV3 set to address(0) are not validated but are still added to the mapping, which can lead to invalid entries in the _aggregatorsData mapping.

## Impact
Invalid Entries: The _aggregatorsData mapping may contain entries with aggregatorV3 set to address(0), which are likely invalid and undesired.
Inconsistent Data: The presence of invalid entries in the mapping can lead to inconsistencies and potential errors in subsequent operations that rely on this data.
Security Risks: If the _aggregatorsData mapping is used in critical operations, such as price feeds for financial transactions, invalid entries can pose security risks and financial discrepancies.

## Code Snippet
https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/oracles/ChainlinkOracle.sol#L45

```solidity 
    function setChainlinkOracles(
        address vault,
        address[] calldata tokens,
        AggregatorData[] calldata data_
    ) external {
        IDefaultAccessControl(vault).requireAdmin(msg.sender);
        if (tokens.length != data_.length) revert InvalidLength();
        for (uint256 i = 0; i < tokens.length; i++) {
            if (data_[i].aggregatorV3 == address(0)) continue;
            _validateAndGetPrice(data_[i]);
        }
        for (uint256 i = 0; i < tokens.length; i++) {
            _aggregatorsData[vault][tokens[i]] = data_[i];
        }
        emit ChainlinkOracleSetChainlinkOracles(
            vault,
            tokens,
            data_,
            block.timestamp
        );
    }
```
## Tool used

Manual Review

## Recommendation
Add the same validation check in the second loop to ensure that entries with aggregatorV3 set to address(0) are not added to the _aggregatorsData mapping. Here is the corrected function:

```diff
function setChainlinkOracles(
    address vault,
    address[] calldata tokens,
    AggregatorData[] calldata data_
) external {
    IDefaultAccessControl(vault).requireAdmin(msg.sender);
    if (tokens.length != data_.length) revert InvalidLength();

    for (uint256 i = 0; i < tokens.length; i++) {
        if (data_[i].aggregatorV3 == address(0)) continue;
        _validateAndGetPrice(data_[i]);
    }

    for (uint256 i = 0; i < tokens.length; i++) {
+       if (data_[i].aggregatorV3 == address(0)) continue;
        _aggregatorsData[vault][tokens[i]] = data_[i];
    }

    emit ChainlinkOracleSetChainlinkOracles(
        vault,
        tokens,
        data_,
        block.timestamp
    );
}
```

Duplicate of #245

**Comment by recursiveEth** [comment]
Escalate 
i want you to look at the issue number is #173, it's a valid issue because it iterates over the tokens array, skipping entries where data_[i].aggregatorV3 is address(0) and validating the rest, check the vulnerability details again.
Even though it's a admin function there is mistake in code, they have prior check for zero aggregator address which means they have additional check and adding the same address 0 in next statement is code mistake  as there the whole segment of code dedicated to handling such paths it doesn't depend of admin please have a look carefully, thank you

**Comment by sherlock-admin3** [comment]
> Escalate 
> i want you to look at the issue number is #173, it's a valid issue because it iterates over the tokens array, skipping entries where data_[i].aggregatorV3 is address(0) and validating the rest, check the vulnerability details again.
> Even though it's a admin function there is mistake in code, they have prior check for zero aggregator address which means they have additional check and adding the same address 0 in next statement is code mistake  as there the whole segment of code dedicated to handling such paths it doesn't depend of admin please have a look carefully, thank you   

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by z3s** [comment]
I agree with you, it's better to have that extra check, but it's still an admin function.
In my opinion this issue is valid Low/Info.

**Comment by recursiveEth** [comment]
Escalate
@z3s i am not saying about that admin is malicious or by choice they will enter the wrong values, the things they didn't handle the case properly if they are checking for the possible scenarios in one statement they should have done that in next for loop also but they are inserting the wrong values in the mapping admin role cannot cover this issue its the wrong code to implement the function, if admin could do all the things properly then there will never be requirement of basic address(0) check globally, and they didn't implement properly whole price fetch mechanism will make output wrong value you can direct to #246 for more detail for this issue how can this impact, i request you to check out the vulnerability once again, thank you

**Comment by sherlock-admin3** [comment]
> Escalate
> @z3s i am not saying about that admin is malicious or by choice they will enter the wrong values, the things they didn't handle the case properly if they are checking for the possible scenarios in one statement they should have done that in next for loop also but they are inserting the wrong values in the mapping admin role cannot cover this issue its the wrong code to implement the function, if admin could do all the things properly then there will never be requirement of basic address(0) check globally, and they didn't implement properly whole price fetch mechanism will make output wrong value you can direct to #246 for more detail for this issue how can this impact, i request you to check out the vulnerability once again, thank you

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Both of these escalations will be rejected, cause the main report is escalated, hence, this report's escalations won't affect the reward distribution.

**Comment by WangSecurity** [comment]
Result:
Invalid
Duplicate of #245

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [recursiveEth](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/173/#issuecomment-2227746681): rejected
- [recursiveEth](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/173/#issuecomment-2231123375): rejected
