### ISSUE TITLE
recursiveEth - Unbounded Operations in `processAll` Function Leading to Excessive Gas Consumption and Potential Gas Loss/

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-mellow-judging#179]
recursiveEth

High

# Unbounded Operations in `processAll` Function Leading to Excessive Gas Consumption and Potential Gas Loss/

## Summary
The `processAll` function is designed to process all pending withdrawal requests for a vault. However, it suffers from potential gas consumption issues due to unbounded operations in the `pendingWithdrawers` function and subsequent operations within the processWithdrawals function. This can lead to the function becoming uncallable if the number of pending withdrawers grows too large, potentially resulting in gas-related failures, inefficiencies, and gas loss due to reversion without refunds.

Given the `processAll` function described earlier, if the function runs out of gas due to the extensive operations involved (e.g., processing a large number of pending withdrawers or transferring many tokens), the gas used up to the point of failure will not be refunded. 

## Vulnerability Detail
The vulnerability arises from several points in the processAll function:

1. Unbounded pendingWithdrawers Retrieval: The processAll function calls vault.pendingWithdrawers(), which in turn calls the values function in EnumerableSet.sol. This function copies the entire storage set to memory, an operation that can be very expensive in terms of gas. The cost of this operation is unbounded and increases with the size of the set.
```solidity
function values(Bytes32Set storage set) internal view returns (bytes32[] memory) {
    bytes32[] memory store = _values(set._inner);
    bytes32[] memory result;

    /// @solidity memory-safe-assembly
    assembly {
        result := store
    }

    return result;
}

```
2. Iteration Over Users: After retrieving the pending withdrawers, processAll calls _processWithdrawals, which iterates over the array of users. The cost of this loop is also unbounded and increases with the number of users.
 ```solidity
for (uint256 i = 0; i < users.length; i++) {
    address user = users[i];
    if (!_pendingWithdrawers.contains(user)) continue;
    // Further processing
}

```
3.Complexity of Processing Each Withdrawal: For each user, the function calls analyzeRequest, potentially modifies balances, and transfers tokens. This involves additional nested loops and calls, further increasing the gas consumption.
```solidity

for (uint256 j = 0; j < s.tokens.length; j++) {
    s.erc20Balances[j] -= expectedAmounts[j];
    IERC20(s.tokens[j]).safeTransfer(
        request.to,
        expectedAmounts[j]
    );
}
```
Due to these unbounded operations, the function may consume an excessive amount of gas, leading to reversion and loss of gas fees without completing the intended operations.
## Impact
Gas Exhaustion: The processAll function may revert due to exceeding the gas limit, especially if the number of pending withdrawers is large.
Inefficiency: Users calling the function may incur significant gas costs without successfully processing withdrawals, leading to inefficiencies and potential financial losses.
Uncallable Function: If the number of pending withdrawers grows too large, the function may become effectively uncallable, preventing any withdrawals from being processed.
## Code Snippet
https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/strategies/DefaultBondStrategy.sol#L84

```solidity 
function processAll() external {
    _requireAtLeastOperator();
    _processWithdrawals(vault.pendingWithdrawers());
}

function pendingWithdrawers() external view returns (address[] memory) {
    return _pendingWithdrawers.values();
}

function values(Bytes32Set storage set) internal view returns (bytes32[] memory) {
    bytes32[] memory store = _values(set._inner);
    bytes32[] memory result;

    /// @solidity memory-safe-assembly
    assembly {
        result := store
    }

    return result;
}

function processWithdrawals(
    address[] memory users
) external nonReentrant returns (bool[] memory statuses) {
    _requireAtLeastOperator();
    statuses = new bool[](users.length);
    ProcessWithdrawalsStack memory s = calculateStack();
    uint256 burningSupply = 0;
    for (uint256 i = 0; i < users.length; i++) {
        address user = users[i];
        if (!_pendingWithdrawers.contains(user)) continue;
        WithdrawalRequest memory request = _withdrawalRequest[user];
        (
            bool isProcessingPossible,
            bool isWithdrawalPossible,
            uint256[] memory expectedAmounts
        ) = analyzeRequest(s, request);

        if (!isProcessingPossible) {
            _cancelWithdrawalRequest(user);
            continue;
        }
        if (!isWithdrawalPossible) continue;

        for (uint256 j = 0; j < s.tokens.length; j++) {
            s.erc20Balances[j] -= expectedAmounts[j];
            IERC20(s.tokens[j]).safeTransfer(
                request.to,
                expectedAmounts[j]
            );
        }

        burningSupply += request.lpAmount;
        delete _withdrawalRequest[user];
        _pendingWithdrawers.remove(user);             
        statuses[i] = true;
    }

    if (burningSupply == 0) return statuses;
    _burn(address(this), burningSupply);
    emit WithdrawalsProcessed(users, statuses);

    address callback = configurator.withdrawalCallback();
    if (callback == address(0)) return statuses;
    IWithdrawalCallback(callback).withdrawalCallback();
    emit WithdrawCallback(callback);
}

```
## Tool used

Manual Review
Gas Estimation and Optimization: Estimate gas usage for processing and optimize loops and function calls to reduce gas consumption where possible.

## Recommendation
![Screenshot 2024-06-27 154000](https://github.com/sherlock-audit/2024-06-mellow-recursiveEth/assets/146105220/27806d6f-aaf7-4782-af9d-5c1377c2b892)

**Comment by recursiveEth** [comment]
Escalate
issue number is #179, there is gas issue which can always revert there are some-other protocols which use the enumerable library and don't use that function for fetching the value, due to its gas cost of coping while storage it cost  minimum gas of 100, and further more there lot of external call which are called which can be lot expensive
have a look, Thank you
![image](https://github.com/user-attachments/assets/5700b9cd-612b-4213-8cb2-6af0bea56637)

**Comment by sherlock-admin3** [comment]
> Escalate
> issue number is #179, there is gas issue which can always revert there are some-other protocols which use the enumerable library and don't use that function for fetching the value, due to its gas cost of coping while storage it cost  minimum gas of 100, and further more there lot of external call which are called which can be lot expensive
> have a look, Thank you
> ![image](https://github.com/user-attachments/assets/5700b9cd-612b-4213-8cb2-6af0bea56637)
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by z3s** [comment]
Hey, @recursiveEth There is `processWithdrawals` function so the protocol can handles withdrawals fixed amount of users at a time, so there's no withdrawals functionality loss.
In my opinion this issue is Informational.

**Comment by recursiveEth** [comment]
@z3s there is no issue if using `processWithdrawals` but when they choose to handle all the withdrawals at the same time it will result in DOS. it making n number of external call issue is regarding not implementing the function for withdrawals in flexible manner result in DOS

**Comment by WangSecurity** [comment]
I agree with the lead judge, since `processWithdrawals` will still work in that environment and the withdrawals are possible, I believe it's gas opt issue. Planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [recursiveEth](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/179/#issuecomment-2227776872): rejected
