### ISSUE TITLE
ArsenLupin - _stethToWsteth method revert, resulting in DoS

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-mellow-judging#181]
ArsenLupin

High

# _stethToWsteth method revert, resulting in DoS

## Summary
stEth::safeTransferFrom could transfer 1-2 less way, which could lead to the function revert because the same amount is passed into the _stethToWsteth method.

## Vulnerability Detail
**DepositWrapper.sol**

```solidity
if (token == steth) {
IERC20(steth).safeTransferFrom(sender, wrapper, amount);
amount = _stethToWsteth(amount);
```

- Almost the same issue was found on the Sherlock contest.
    
    [[Solodit](https://solodit.xyz/issues/h-2-many-cases-stethtransferfrom-will-transfer-1-2-less-way-which-would-result-in-revert-in-consequent-functions-because-of-not-enough-balance-sherlock-sophon-farming-contracts-git)](https://solodit.xyz/issues/h-2-many-cases-stethtransferfrom-will-transfer-1-2-less-way-which-would-result-in-revert-in-consequent-functions-because-of-not-enough-balance-sherlock-sophon-farming-contracts-git)
    
- The vulnerability discussion could be found here https://github.com/lidofinance/lido-dao/issues/442

## Impact
Functionality DoS.

## Code Snippet
https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/utils/DepositWrapper.sol#L55-L57

## Tool used
Manual Review

## Recommendation
Use lido recommendation to utilize transferShares function. You could also check the balances (before/after) and take the delta on it.

**Comment by ArsenSecurity** [comment]
Escalate 
It is a valid issue. It is a valid dup of the #299 issue, as well of others dups.
Additionaly, the same issue was found on previous contest, graded as a high issue 
https://github.com/sherlock-audit/2024-05-sophon-judging/issues/63

**Comment by sherlock-admin3** [comment]
> Escalate 
> It is a valid issue. It is a valid dup of the #299 issue, as well of others dups.
> Additionaly, the same issue was found on previous contest, graded as a high issue 
> https://github.com/sherlock-audit/2024-05-sophon-judging/issues/63

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by z3s** [comment]
Can anyone find a tx on etherscan where this happen!? because I checked dozen stETH transfers and non of them have this issue.

**Comment by blckhv** [comment]
https://docs.lido.fi/guides/lido-tokens-integration-guide/#1-2-wei-corner-case
https://github.com/lidofinance/lido-dao/issues/442

**Comment by z3s** [comment]
Yeah, etherscan's Transaction Details isn't showing correct info for this issue, I should check event logs.
so depositing stETH get DoSed most of time. I think this submission and it's duplicates should be valid Mediums.

**Comment by WangSecurity** [comment]
Firstly, advice for all in this issue, if your issue is invalid and its grouped into the family, like this one with #299 being the main report, please escalate the main report.

Secondly, about the escalation. I believe this issue is not sufficient to be a valid duplicate, since it doesn't identify the root cause (why there would be 1-2 wei less?), doesn't identify a medium severity impact (functionality DOS by itself is not medium), and doesn't have a valid vulnerability or attack path.

I'll review #299 if it's indeed a valid issue, but this escalation will be rejected and deduped if #299 is valid.

**Comment by WangSecurity** [comment]
For everyone interested in #299 being valid, please look at discussion under #276 issue.

**Comment by ArsenSecurity** [comment]
@WangSecurity could you please explain why my issue is not sufficient duplicate, if it explains the same bug?

_After looking deeper into https://github.com/sherlock-audit/2024-06-mellow-judging/issues/181, I see it's not a sufficient duplicate, hence, the escalation there will be rejected either way. Hence, I'll make this escalation as the main one for https://github.com/sherlock-audit/2024-06-mellow-judging/issues/299 issue family.
Plan to accept the escalation and leave the issue as it is._

**Comment by WangSecurity** [comment]
Based on my comment [here](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/181#issuecomment-2234367416):

> Secondly, about the escalation. I believe this issue is not sufficient to be a valid duplicate, since it doesn't identify the root cause (why there would be 1-2 wei less?), doesn't identify a medium severity impact (functionality DOS by itself is not medium), and doesn't have a valid vulnerability or attack path.

The report doesn't qualify for the [Duplication Requirements](https://github.com/sherlock-protocol/sherlock-v2-docs/blob/29a019b8690eb01df3587868c4d7eac1e3459bda/audits/judging/judging/README.md#ix-duplication-rules)

The decision remains the same, planning to reject the escalation and de-dup this issue in case #299 becomes valid.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Senya123](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/181/#issuecomment-2228738383): rejected
