### ISSUE TITLE
ArsenLupin - Oracle assumes 1=1 peg of stETH to ETH

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-mellow-judging#197]
ArsenLupin

High

# Oracle assumes 1=1 peg of stETH to ETH

## Summary
`WStethRatiosAggregatorV3` contract serves as an Oracle, providing the `latestRoundData` of the `wsteth` token. The problem is, that it assumes that 1 steth == 1 eth. Even though both tokens have a tendency to keep the peg, this hasn't been always the case as it can be seen in [[this charth](https://nomics.com/exchanges/curve-curve-finance-ethereum/markets/0xae7ab96520de3a18e5e111b5eaab095312d7fe84-0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee)](https://nomics.com/exchanges/curve-curve-finance-ethereum/markets/0xae7ab96520de3a18e5e111b5eaab095312d7fe84-0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee) or [[this dashboard](https://dune.com/LidoAnalytical/Curve-ETHstETH)](https://dune.com/LidoAnalytical/Curve-ETHstETH). There have been many episodes of market volatility that affected the price of stETH, notably the one in last June when stETH traded at ~0.93 ETH.

Let’s take a look on the `getAnswer` function.

```solidity
function getAnswer() public view returns (int256) {
        return int256(IWSteth(wsteth).getStETHByWstETH(10 ** decimals));
    }
```

This function is designed to estimate the current value in ETH of a single unit (1e18) of the underlying asset. In this implementation, the function queries the amount of stETH for one unit (1e18) of wstETH and returns that value, clearly indicating a conversion rate of 1 stETH to 1 ETH.

Similar issue could be found here → https://solodit.xyz/issues/h-06-wsteth-derivative-assumes-a-11-peg-of-steth-to-eth-code4rena-asymmetry-finance-asymmetry-contest-git

## Vulnerability Detail
    - If the market value of stETH deviates from ETH, this function might return an inaccurate estimate. For instance, if stETH is worth less than 1 ETH, the function will overestimate the value of wstETH.
    - Any financial calculation relying on `getAnswer ` will be incorrect if the peg assumption fails, potentially leading to mispricing, incorrect collateralization, or erroneous trading decisions.

```solidity
function getAnswer() public view returns (int256) {
        return int256(IWSteth(wsteth).getStETHByWstETH(10 ** decimals));
    }
```

## Impact
Incorrect prices could be returned

## Code Snippet
https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/oracles/WStethRatiosAggregatorV3.sol#L15-L16

## Tool used
Manual Review

## Recommendation
Don’t assume stETH = ETH 1:1. Re-code the wsETH oracle. Use the chainlink oracle

**Comment by ArsenSecurity** [comment]
Escalate
The vulnerability clearly shows the incorrect "assumption". Our work as a researchers is to find a valid bugs which could harm users, the vulnerability clearly shows that the assumption is incorrect which could potentially lead to the harmful consequences

**Comment by sherlock-admin3** [comment]
> Escalate
> The vulnerability clearly shows the incorrect "assumption". Our work as a researchers is to find a valid bugs which could harm users, the vulnerability clearly shows that the assumption is incorrect which could potentially lead to the harmful consequences

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by InfectedIsm** [comment]
I would add that even Lido states that wstETH price should be obtained by composing the 2 price feeds:

> _https://docs.lido.fi/guides/lido-tokens-integration-guide#stethwsteth-as-collateral_
> Robust price sources are required for listing on most money markets, with ChainLink price feeds being the industry standard. The default option to use is exchange [rate feeds](https://docs.lido.fi/guides/lido-tokens-integration-guide#sttokens-steth-and-wsteth) with an option to compose arbitrary feeds:
>```solidity
>'wstETH/X price feed' = 'wstETH/stETH rate feed' × 'ETH/X price feed'
>```

**Comment by z3s** [comment]
The protocol team comment on discord chat:
> we assume `1 steth == 1 weth`, at least for current deployments

**Comment by blckhv** [comment]
1. If the assumption was correct there will not be stETH/ETH Chainlink oracle in first place
2. The price deviation can be clearly seen by looking at the oracle's price graph - https://data.chain.link/feeds/ethereum/mainnet/steth-eth

**Comment by WangSecurity** [comment]
I believe this report, specifically, doesn't have a medium impact.

> Incorrect prices could be returned

I believe it's a root cause that the prices are not equal, and the only impact in the report is:

> potentially leading to mispricing, incorrect collateralization, or erroneous trading decisions

I don't see it as sufficient proof of medium impact.

Planning to reject the escalation and leave the issue as it is. I'll review #29 additionally (the main report of this family), and if it's in the end valid, I will dedup this report.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Senya123](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/197/#issuecomment-2228101364): rejected
