### ISSUE TITLE
scammed - Vault::delegateCall doesn’t check for execution success

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-mellow-judging#205]
scammed

High

# Vault::delegateCall doesn’t check for execution success

## Summary

`delegateCall` execution `success` is not checked.

## Vulnerability Detail

Since `Vault:delegateCall` is used multiple times, and mostly the call data is a function interacting with external calls, it's common for each of these calls to revert is any cases and thus the `success` of the `delegateCall` to be `false`. But this is unchecked, which will skip failure and continue executing the function.

```solidity
function delegateCall(
    address to,
    bytes calldata data
) external returns (bool success, bytes memory response) {
    _requireAtLeastOperator();
    if (!configurator.isDelegateModuleApproved(to)) revert Forbidden();
    IValidator validator = IValidator(configurator.validator());
    validator.validate(
        msg.sender,
        address(this),
        abi.encodeWithSelector(msg.sig, to, data)
    );
    validator.validate(address(this), to, data);
    (success, response) = to.delegatecall(data); // @audit success not checkeds
    emit DelegateCall(to, data, success, response);
}
```

Let’s consider the example when `StakingModule::convert` which is called through `vault::delegateCall` fail and the  `SimpleDVTStakingStrategy::processWithdrawals` continues its execution but without increasing the `wstETH` balance. 

Then `vault::calculateStack` and especially `s.totalValue` will be lowered, since the weth has not been able to be converted to `wstETH`.

```solidity
  function calculateStack()
      public
      view
      returns (ProcessWithdrawalsStack memory s)
  {
      (address[] memory tokens, uint256[] memory amounts) = underlyingTvl();//tokens[0] = wstETH
     ...MORE CODE
      IPriceOracle priceOracle = IPriceOracle(configurator.priceOracle());
      for (uint256 i = 0; i < tokens.length; i++) {
          uint256 priceX96 = priceOracle.priceX96(address(this), tokens[i]);
          s.totalValue += FullMath.mulDiv(amounts[i], priceX96, Q96);//wstETH.balanceOf(vault) < weth.balanceOf(vault)
          s.ratiosX96Value += FullMath.mulDiv(s.ratiosX96[i], priceX96, Q96);
          s.erc20Balances[i] = IERC20(tokens[i]).balanceOf(address(this));
      }
  }
```

And from there, all the users who specified tighter slippage will have their requests cancelled due to insufficient `expectedAmount`

```solidity
function analyzeRequest(
  ProcessWithdrawalsStack memory s,
  WithdrawalRequest memory request
) public pure returns (bool, bool, uint256[] memory expectedAmounts) {
  uint256 lpAmount = request.lpAmount;
  if (
      request.tokensHash != s.tokensHash || request.deadline < s.timestamp
  ) return (false, false, expectedAmounts);

  uint256 value = FullMath.mulDiv(lpAmount, s.totalValue, s.totalSupply);
  value = FullMath.mulDiv(value, D9 - s.feeD9, D9);
  uint256 coefficientX96 = FullMath.mulDiv(value, Q96, s.ratiosX96Value);

  uint256 length = s.erc20Balances.length;
  expectedAmounts = new uint256[](length);
  for (uint256 i = 0; i < length; i++) {
      uint256 ratiosX96 = s.ratiosX96[i];
      expectedAmounts[i] = ratiosX96 == 0
          ? 0
          : FullMath.mulDiv(coefficientX96, ratiosX96, Q96);
      if (expectedAmounts[i] >= request.minAmounts[i]) continue;//@audit
      return (false, false, expectedAmounts);
  }
  for (uint256 i = 0; i < length; i++) {
      if (s.erc20Balances[i] >= expectedAmounts[i]) continue;
      return (true, false, expectedAmounts);
  }
  return (true, true, expectedAmounts);
}
```

This is only one of all the possible scenarios that will happen in case `delegateCall` silently fails.

## Impact

If the function called via `delegatecall` fails, execution of `Vault:delegateCall` will continue, assuming the call succeeded.

## Code Snippet

https://github.com/sherlock-audit/2024-06-mellow/blob/26aa0445ec405a4ad637bddeeedec4efe1eba8d2/mellow-lrt/src/Vault.sol#L280

https://github.com/mellow-finance/mellow-lrt/blob/dev-symbiotic-deploy/src/Vault.sol#L529

https://github.com/mellow-finance/mellow-lrt/blob/dev-symbiotic-deploy/src/Vault.sol#L476C1-L504C6

## Tool used

Manual Review

## Recommendation

Add check if `success` is true.

Duplicate of #93

**Comment by 0x3b33** [comment]
Escalate

It is not explained very clearly in the selected report, but if we look at the example written in this one, you will see that the problem is valid and all low-level call successes should never be missed and unchecked, no matter where or how they are used.

In the example above (1 of 2 places where `Vault::delegateCall` is used) `StakingModule::convert()` will fail due to passing the same `amount` as `weth/ETH/stETH`, but as reported in [[#203](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/203)](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/203) and also apparently very easy to be understood, submitting **X amount** of ETH to `stETH.submit` will not return the same value in `stETH` and then calling `wstETH::wrap` with the same **X amount** will fail because there will not be enough stETH balance.

```solidity
function convert(uint256 amount) external onlyDelegateCall {
    _wethToWSteth(amount);
}

// Using same amount as WETH/ETH/stETH
function _wethToWSteth(uint256 amount) private {
    IWeth(weth).withdraw(amount);
    ISteth(steth).submit{value: amount}(address(0));
    IERC20(steth).safeIncreaseAllowance(address(wsteth), amount);
    IWSteth(wsteth).wrap(amount);
}
```

```solidity
/**
 * @notice Send funds to the pool with optional _referral parameter
 * @dev This function is alternative way to submit funds. Supports optional referral address.
 * @return Amount of StETH shares generated <------------------------ shares not the same value as msg.value, because the shares are based on current totalShares and pooled stETH
 */
function submit(address _referral) external payable returns (uint256) {
    return _submit(_referral);
}
```

Then processWithdrawals() will continue its execution even when the weth → wsteth convert has failed.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> It is not explained very clearly in the selected report, but if we look at the example written in this one, you will see that the problem is valid and all low-level call successes should never be missed and unchecked, no matter where or how they are used.
> 
> In the example above (1 of 2 places where `Vault::delegateCall` is used) `StakingModule::convert()` will fail due to passing the same `amount` as `weth/ETH/stETH`, but as reported in [[#203](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/203)](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/203) and also apparently very easy to be understood, submitting **X amount** of ETH to `stETH.submit` will not return the same value in `stETH` and then calling `wstETH::wrap` with the same **X amount** will fail because there will not be enough stETH balance.
> 
> ```solidity
> function convert(uint256 amount) external onlyDelegateCall {
>     _wethToWSteth(amount);
> }
> 
> // Using same amount as WETH/ETH/stETH
> function _wethToWSteth(uint256 amount) private {
>     IWeth(weth).withdraw(amount);
>     ISteth(steth).submit{value: amount}(address(0));
>     IERC20(steth).safeIncreaseAllowance(address(wsteth), amount);
>     IWSteth(wsteth).wrap(amount);
> }
> ```
> 
> ```solidity
> /**
>  * @notice Send funds to the pool with optional _referral parameter
>  * @dev This function is alternative way to submit funds. Supports optional referral address.
>  * @return Amount of StETH shares generated <------------------------ shares not the same value as msg.value, because the shares are based on current totalShares and pooled stETH
>  */
> function submit(address _referral) external payable returns (uint256) {
>     return _submit(_referral);
> }
> ```
> 
> Then processWithdrawals() will continue its execution even when the weth → wsteth convert has failed.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by InfectedIsm** [comment]
success is returned by the function:

```solidity
function delegateCall(
    address to,
    bytes calldata data
) external returns (bool success, bytes memory response) {   <<@ success returned
    /* ... some code ... */
    );
    (success, response) = to.delegatecall(data);  <<@ success being returned
    emit DelegateCall(to, data, success, response);
}
```

**Comment by blckhv** [comment]
Does the execution reverts in case of success being false?

**Comment by InfectedIsm** [comment]
@blckhv no, but delegateCall is meant to be called from another contract. This allow for more flexibility on how to behave on an unsuccessful `delegatecall`.
the `Vault::delegateCall` is like a wrapper around `delegatecall` adding role permission, its then up to the caller to check the success value and act as desired

**Comment by blckhv** [comment]
@InfectedIsm 
Thanks for the conversation ser. Do any of the Strategies in scope use the **success** returned to terminate the execution?

**Comment by InfectedIsm** [comment]
> @InfectedIsm Thanks for the conversation ser. Do any of the Strategies in scope use the **success** returned to terminate the execution?

Sentiments are shared ser
No, but then if issue there is, issue is located in those strategies, and specific to the function that is called through `Vault::delegateCall`, as they have the `success` parameter provided allowing them to act accordingly.
As I said, `Vault::delegateCall` act as a wrapper around a standard `delegatecall`, by adding role permission capabilities, nothing more, nothing less.
Non returned value from `delegatecall` isn't a vulnerability by itself, it become a vulnerability if the call can revert and an impact is shown in the context of the project.

**Comment by WangSecurity** [comment]
Based on the above discussion, I believe it's not an issue and up to the caller to check if the call was successful. Planning to reject the escalation and leave the issue as it is.

**Comment by Slavchew** [comment]
The above discussion only confirms that the low-level calls (`call` and `delegateCall`) must check the `success` value. @InfectedIsm only told that `Vault::delegateCall` act as a wrapper and should not check for `success` and that contracts using that wrapper should check. This is exactly what is specified in the problem and in the escalation. 


`SimpleDVTStakingStrategy::processWithdrawals` calls `Vault::delegateCall` with `StakingModule.convert` which will revert because WETH -> ETH -> stETH -> wstETH is not the same value. If that was true, I'd be the first guy to swap 1 WETH for 1 wstETH since they have almost a $600 difference. But this is another problem reported by many people.

When `StakingModule.convert` reverts, `delegateCall` `success` will be false, but the function will continue its execution.
I don't think I can be any clearer than that, it's already been explained 3 times.

```js
function processWithdrawals(
        address[] memory users,
        uint256 amountForStake
    ) external returns (bool[] memory statuses) {
        _requireAtLeastOperator();
        if (users.length == 0) return statuses;
        emit ProcessWithdrawals(users, amountForStake, msg.sender);

        if (amountForStake == 0) return vault.processWithdrawals(users);

        vault.delegateCall(
            address(stakingModule),
            abi.encodeWithSelector(
                IStakingModule.convert.selector,
                amountForStake
            )
        );   // This use the vault.delegateCall which will return success false in that case, and this is not check.

        statuses = vault.processWithdrawals(users);
        address wsteth = stakingModule.wsteth();
        uint256 balance = IERC20(wsteth).balanceOf(address(vault));
        if (balance > maxAllowedRemainder) revert LimitOverflow();
    }
```

```js
function _wethToWSteth(uint256 amount) private {
        IWeth(weth).withdraw(amount);
        ISteth(steth).submit{value: amount}(address(0));
        IERC20(steth).safeIncreaseAllowance(address(wsteth), amount);
        IWSteth(wsteth).wrap(amount);
    }
```

You can also read that: https://www.rareskills.io/post/delegatecall

**Comment by InfectedIsm** [comment]
After reading again, I recognize my message was not explicit enough about my point, sorry for that.
So, my point is that fixing #203 would make the delegatecall not revert.
While I agree this is really bad practice to not check the success value, the issue is located in `_wethToWSteth` which is part of the scope of the contest, the root cause isn't the delegatecall itself, but how the weth -> steth -> wsteth conversion is executed.
Fixing #203 would fix both issues, this was my point.

**Comment by Slavchew** [comment]
This is a completely new opinion from you ser. And thus, even if fixing the other issue might fix this, you can't rely on calling 3 external protocols (weth, stETH, wstETH) always to work, and not check for `success`.

You can't rely on assumptions that everything is fine and skip this check, which can prevent a much larger impact on the protocol if something happens on these external calls.

Also `Vault::delegateCall` is used in other cases.

I will only respond to @WangSecurity questions and concerns from now on.

**Comment by InfectedIsm** [comment]
You are right, I kind of overextended here. 
Anyway, I think I have raised every relevant point from my side, thank you for your patience ser.

**Comment by 10xhash** [comment]
Intentionally not checking the return value is acknowledged in the past audit report https://github.com/mellow-finance/mellow-lrt/blob/dev-symbiotic-deploy/audits/202406_Statemind/Mellow%20LRT%20report%20with%20deployment.pdf. This was acknowledged for the deposit function

For the withdrawal function: 
1. It is not required to revert incase the amount conversion has failed. The amount conversion is done to support more withdrawals and incase the amount has not been converted, whatever is possible to be withdrawn with the existing steth can be withdrawn
2. The weth to wsteth conversion will not fail, below is the flow:
https://github.com/sherlock-audit/2024-06-mellow/blob/26aa0445ec405a4ad637bddeeedec4efe1eba8d2/mellow-lrt/src/modules/obol/StakingModule.sol#L77-L82
```solidity
    function _wethToWSteth(uint256 amount) private {
        IWeth(weth).withdraw(amount);
        ISteth(steth).submit{value: amount}(address(0));
        IERC20(steth).safeIncreaseAllowance(address(wsteth), amount);
        IWSteth(wsteth).wrap(amount);
    }
```
using x for the amount

IWeth(weth).withdraw(x);
will result in x amount of eth

ISteth(steth).submit{value: amount}(address(0));
will result in getSharesByPooledEth(x) amount of shares being minted to the user
https://github.com/lidofinance/lido-dao/blob/5fcedc6e9a9f3ec154e69cff47c2b9e25503a78a/contracts/0.4.24/Lido.sol#L922-L940

IERC20(steth).safeIncreaseAllowance(address(wsteth), x);
normal approve call

IWSteth(wsteth).wrap(x);
will attempt to transferFrom msg.sender, x amount of steth  
https://github.com/lidofinance/lido-dao/blob/5fcedc6e9a9f3ec154e69cff47c2b9e25503a78a/contracts/0.6.12/WstETH.sol#L53-L57
the x amount of steth gets converted to shares computed using getSharesByPooledEth
https://github.com/lidofinance/lido-dao/blob/5fcedc6e9a9f3ec154e69cff47c2b9e25503a78a/contracts/0.4.24/StETH.sol#L375-L379
this will revert only if the initial getSharesByPooledEth(x) was less than current getSharesByPooledEth(x)
This will not occur as getSharesByPooledEth rounds down
https://github.com/lidofinance/lido-dao/blob/5fcedc6e9a9f3ec154e69cff47c2b9e25503a78a/contracts/0.4.24/StETH.sol#L300-L304
```solidity
    function getSharesByPooledEth(uint256 _ethAmount) public view returns (uint256) {
        return _ethAmount
            .mul(_getTotalShares())
            .div(_getTotalPooledEther());
    }
```

**Comment by Slavchew** [comment]
`getSharesByPooledEth(x)` will not return X amount of stETH shares, in fact this is the amount that will be returned if you call the function now.

<img width="1508" alt="image" src="https://github.com/user-attachments/assets/beb410de-1ceb-4c8d-a2c0-61f6cbe4bd70">

With that said, `stETH.submit` will return 0.85e18 and then will try to wrap X amount (using 1e18), which is much more than the amount of stETH minted after `submit()`.

https://etherscan.deth.net/address/0x7f39c581f595b53c5cb19bd0b3f8da6c935e2ca0

```js
    function wrap(uint256 _stETHAmount) external returns (uint256) {
        require(_stETHAmount > 0, "wstETH: can't wrap zero stETH");
        uint256 wstETHAmount = stETH.getSharesByPooledEth(_stETHAmount);
        _mint(msg.sender, wstETHAmount);
        stETH.transferFrom(msg.sender, address(this), _stETHAmount);
        return wstETHAmount;
    }
```

Wrap() will then calculate `wstETHAmount` based on X, not the actual stETH shares that have been mined, and also the transfer below will fail because there are not enough stETH shares in the contract.

Saying this again, if I can convert X amount of WETH to the same X amount of wstETH, I will do this not auditing since both have a $600 difference. It's impossible to unwrap ETH, stake for stETH, and then wrap for wstETH and get the same value of wstETH.

**Comment by WangSecurity** [comment]
Based on the above comment, I believe the issue has to remain invalid. Especially, based on the reason that this finding was found, acknowledged and not fixed in the previous report.

Planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid 
Duplicate of #93

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0x3b33](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/205/#issuecomment-2231791440): rejected
