### ISSUE TITLE
scammed - DefaultBondStrategy::depositCallback should not deposit the entire tvl

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-mellow-judging#208]
scammed

High

# DefaultBondStrategy::depositCallback should not deposit the entire tvl

## Summary

Vault depositors can grief both withdrawals because `depositCallback` always deposits the entire Vault balance, instead of only the new deposit.

## Vulnerability Detail

When Vault has a callback address configured, all the deposits will end up calling the `depositCallback` that takes the **entire balance** of the Vault, so it can be further deposited in the bonds in order to receive yield:

```solidity
function depositCallback(uint256[] memory, uint256) external override {
    if (msg.sender != address(vault)) _requireAtLeastOperator();
    _deposit();
}

function _deposit() private {
    ITvlModule.Data[] memory tvl = erc20TvlModule.tvl(address(vault));
    for (uint256 i = 0; i < tvl.length; i++) {
        address token = tvl[i].token;
        bytes memory data_ = tokenToData[token];
        if (data_.length == 0) continue;
        Data[] memory data = abi.decode(data_, (Data[]));
        for (uint256 j = 0; j < data.length; j++) {
            uint256 amount = FullMath.mulDiv(
                tvl[i].amount,
                data[j].ratioX96,
                Q96
            );
            if (amount == 0) continue;
            vault.delegateCall(
                address(bondModule),
                abi.encodeWithSelector(
                    IDefaultBondModule.deposit.selector,
                    data[j].bond,
                    amount
                )
            );
        }
    }
```

Here we can see that `DefaultBondModule::deposit` will use the `amount` received from `Erc20TvlModule::tvl`, instead of the amount that is currently being deposited, leaving the others tokens idling in the `Vault` for withdrawals:

```solidity
contract ERC20TvlModule is IERC20TvlModule, DefaultModule {
    /// @inheritdoc ITvlModule
    function tvl(
        address vault
    ) external view noDelegateCall returns (Data[] memory data) {
        address[] memory tokens = IVault(vault).underlyingTokens();
        data = new Data[](tokens.length);
        for (uint256 i = 0; i < tokens.length; i++) {
            data[i].token = tokens[i];
            data[i].underlyingToken = tokens[i];
            data[i].amount = IERC20(tokens[i]).balanceOf(vault);
            data[i].underlyingAmount = data[i].amount;
        }
    }
}
```

Knowing that malicious user can execute deposits the following issues will occur, depending on which function is being frontrunned:

- `emergencyWithdraw`
    - frontrunning emergency withdrawal when there is a **single underlying token** and every deposit to bond takes all the tokens from the Vault, will either revert the transaction if there are non-zero `minAmounts` specified:
    
    ```solidity
        function emergencyWithdraw(
            uint256[] memory minAmounts,
            uint256 deadline
        )
            external
            nonReentrant
            checkDeadline(deadline)
            returns (uint256[] memory actualAmounts)
        {
    ...MORE CODE
            (address[] memory tokens, uint256[] memory amounts) = baseTvl();
            if (minAmounts.length != tokens.length) revert InvalidLength();
            actualAmounts = new uint256[](tokens.length);
            for (uint256 i = 0; i < tokens.length; i++) {
                if (amounts[i] == 0) {
                    if (minAmounts[i] != 0) revert InsufficientAmount();
                    continue;
                }
                uint256 amount = FullMath.mulDiv(
                    IERC20(tokens[i]).balanceOf(address(this)),
                    request.lpAmount,
                    totalSupply
                );
                if (amount < minAmounts[i]) revert InsufficientAmount();
                IERC20(tokens[i]).safeTransfer(request.to, amount);
                actualAmounts[i] = amount;
            }
            delete _withdrawalRequest[sender];
            _pendingWithdrawers.remove(sender);
            _burn(address(this), request.lpAmount);
            emit EmergencyWithdrawal(sender, request, actualAmounts);
        }
    ```
    
    - or in case user specifies no min amount, i.e. he is willing to lose some tokens instead he ends up receiving 0 tokens back because of the `deposit` transaction executed before has deposit the entire Vault balance.
- `Vault::processWithdrawals`
    - if `processWithdrawals` is called directly from the `Vault`, not from the `DefaultBondStrategy`, withdrawal from all the supported `Bonds` will not be executed:
    
    ```solidity
    function calculateStack()
        public
        view
        returns (ProcessWithdrawalsStack memory s)
    {
        (address[] memory tokens, uint256[] memory amounts) = underlyingTvl();//@audit amounts are zero 
        s = ProcessWithdrawalsStack({
            tokens: tokens,
            ratiosX96: IRatiosOracle(configurator.ratiosOracle())
                .getTargetRatiosX96(address(this), false),
            erc20Balances: new uint256[](tokens.length),
            totalSupply: totalSupply(),
            totalValue: 0,
            ratiosX96Value: 0,
            timestamp: block.timestamp,
            feeD9: configurator.withdrawalFeeD9(),
            tokensHash: keccak256(abi.encode(tokens))
        });
    
        IPriceOracle priceOracle = IPriceOracle(configurator.priceOracle());
        for (uint256 i = 0; i < tokens.length; i++) {
            uint256 priceX96 = priceOracle.priceX96(address(this), tokens[i]);
            s.totalValue += FullMath.mulDiv(amounts[i], priceX96, Q96);//@audit this is zero 
            s.ratiosX96Value += FullMath.mulDiv(s.ratiosX96[i], priceX96, Q96);
            s.erc20Balances[i] = IERC20(tokens[i]).balanceOf(address(this));//@audit this is zero 
        }
    }
    ```
    
    Frontrunning `processWithdrawals` with `deposit` will decrease all the token balances (**or even making it equal to 0, in case there is a single underlying token**), since all of them will be converted to Symbiotic LPTokens in the `DefaultBondModule`.
    
    Then `analyzeRequest` will **fail** because of the calculated underlying token amount being lower than the `minAmount` specified from withdrawal recipient. If we take the scenario with single underlying token, we will receive 0 amount from the `Vault::underlyingTvl` and this same amount is used to calculate the exchange rate of the lpTokens:
    
    ```solidity
    function analyzeRequest(
        ProcessWithdrawalsStack memory s,
        WithdrawalRequest memory request
    ) public pure returns (bool, bool, uint256[] memory expectedAmounts) {
        uint256 lpAmount = request.lpAmount;
        if (
            request.tokensHash != s.tokensHash || request.deadline < s.timestamp
        ) return (false, false, expectedAmounts);
    
        uint256 value = FullMath.mulDiv(lpAmount, s.totalValue, s.totalSupply);
        value = FullMath.mulDiv(value, D9 - s.feeD9, D9);
        uint256 coefficientX96 = FullMath.mulDiv(value, Q96, s.ratiosX96Value);
    
        uint256 length = s.erc20Balances.length;
        expectedAmounts = new uint256[](length);
        for (uint256 i = 0; i < length; i++) {
            uint256 ratiosX96 = s.ratiosX96[i];
            expectedAmounts[i] = ratiosX96 == 0
                ? 0
                : FullMath.mulDiv(coefficientX96, ratiosX96, Q96);
                //@audit less than directly cancels the request
            if (expectedAmounts[i] >= request.minAmounts[i]) continue;
            return (false, false, expectedAmounts);
        }
        for (uint256 i = 0; i < length; i++) {
            if (s.erc20Balances[i] >= expectedAmounts[i]) continue;
            return (true, false, expectedAmounts);
        }
        return (true, true, expectedAmounts);
    } 
    ```
    
    ```solidity
      function processWithdrawals(
          address[] memory users
      ) external nonReentrant returns (bool[] memory statuses) {
          _requireAtLeastOperator();
          statuses = new bool[](users.length);
          ProcessWithdrawalsStack memory s = calculateStack();
          uint256 burningSupply = 0;
          for (uint256 i = 0; i < users.length; i++) {
              address user = users[i];
              if (!_pendingWithdrawers.contains(user)) continue;
              WithdrawalRequest memory request = _withdrawalRequest[user];
              (
                  bool isProcessingPossible,
                  bool isWithdrawalPossible,
                  uint256[] memory expectedAmounts
              ) = analyzeRequest(s, request);
    
              if (!isProcessingPossible) {
              //@audit when insufficient expectedAmounts are calculated
                  _cancelWithdrawalRequest(user);
                  continue;
              }
    ```
    

## Impact

- griefing of withdrawals, excessive gas consumption for the Vault operators

## Code Snippet

https://github.com/mellow-finance/mellow-lrt/blob/dev-symbiotic-deploy/src/Vault.sol#L536-L556

## Tool used

Manual Review

## Recommendation

Possible approach is to invoke `depositCallback` only with the deposited amount, and second access controlled function to perform full deposits.

**Comment by 0x3b33** [comment]
Escalate 

We kindly request this report to be reviewed again as it provides examples where strategy deposits taking the entire Vault’s balance will lead to issues. Additionally, if we look at the `IDepositCallback` interface we will see that there is an `actualAmounts` array that is intended to serve exactly this purpose:

https://github.com/sherlock-audit/2024-06-mellow-SBSecurity/blob/main/mellow-lrt/src/interfaces/utils/IDepositCallback.sol#L11

```solidity
interface IDepositCallback {
  /**
   * @notice Handles the callback after a deposit operation has been executed.
   * @param actualAmounts An array representing the actual amounts of each token that were deposited.
   * @param lpAmount The total amount of LP tokens that were issued as a result of the deposit.
   * @dev This function is intended to be implemented by contracts that need to take further action following a deposit.
   */
  function depositCallback(
      uint256[] memory actualAmounts,
      uint256 lpAmount
  ) external;
}
```

**Comment by sherlock-admin3** [comment]
> Escalate 
> 
> We kindly request this report to be reviewed again as it provides examples where strategy deposits taking the entire Vault’s balance will lead to issues. Additionally, if we look at the `IDepositCallback` interface we will see that there is an `actualAmounts` array that is intended to serve exactly this purpose:
> 
> https://github.com/sherlock-audit/2024-06-mellow-SBSecurity/blob/main/mellow-lrt/src/interfaces/utils/IDepositCallback.sol#L11
> 
> ```solidity
> interface IDepositCallback {
>   /**
>    * @notice Handles the callback after a deposit operation has been executed.
>    * @param actualAmounts An array representing the actual amounts of each token that were deposited.
>    * @param lpAmount The total amount of LP tokens that were issued as a result of the deposit.
>    * @dev This function is intended to be implemented by contracts that need to take further action following a deposit.
>    */
>   function depositCallback(
>       uint256[] memory actualAmounts,
>       uint256 lpAmount
>   ) external;
> }
> ```

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
How long will the DOS last? Is it possible to withdraw in the very next block, for example?

**Comment by blckhv** [comment]
Although it is possible to withdraw in the very next block, the intention of these funds is to stay in the strategy and accumulate yield.
Imagine that this happens often - funds are withdrawn from the strategy with the idea of withdrawals being processed, and someone comes and deposits the entire balance once again in the strategy, leading to the inability for withdrawals to be fulfilled.

**Comment by 0xHuntoor** [comment]
i want to refer to [previous audit report here](https://github.com/mellow-finance/mellow-lrt/blob/dev-symbiotic-deploy/audits/202406_Statemind/Mellow%20LRT%20report%20with%20deployment.pdf)
specifically Medium-04

depositing all tokens back is a design decision 

when we see this statement in [protocol readMe](https://audits.sherlock.xyz/contests/423#:~:text=Please%20discuss%20any,ratio%20lpAmount%20/%20totalSupply.) we see that emergency withdraw is kinda misleading to judge upond

normal flow is operator withdraws, if he delays his act with `emergencyWithdrawalDelay()` then users can call `emergencyWithdraw`

1 block Dos?, i can't see enough harm with the above provided arguments

**Comment by blckhv** [comment]
1. DoS is not mentioned anywhere
2. I can't see any similarities with the issue that you've referenced.
3. I prefer to continue my conversation with the Lead judge as any comments, that only throw random information and make statements from Watsons who participated in this contest are highly subjective.

**Comment by WangSecurity** [comment]
I see that the DOS is not mentioned anywhere, but as I see in both scenarios, the impact of the attack is that either `emergencyWithdraw` or `processsWithdrawals` will fail. That's what I meant by DOS, the attacker in that case would DOS the withdrawal call. But, as I understand the withdrawal call can be repeated in the very next block and would succeed if the attacker doesn't attack again, correct?

> griefing of withdrawals, excessive gas consumption for the Vault operators

And to clarify the impact in the report, you mean the Vault operators would have excessive gas consumptions, because they would have execute withdrawals several times before they're executed sucessfully?

**Comment by blckhv** [comment]
No, I mislead you with my first comment and I'm sorry about the confusion, the withdrawal call can't be repeated in the very next block, because as we mentioned [`isProcessingPossible`](https://github.com/mellow-finance/mellow-lrt/blob/dev-symbiotic-deploy/src/Vault.sol#L554) will evaluate to false and will cancel all the request, each user will have to resubmit his request again. Also, the operator is mentioned to be an automation bot, configured to execute withdrawals once in a while:
![Screenshot 2024-07-20 at 12 40 48 PM](https://github.com/user-attachments/assets/26b34539-a023-4d14-9851-8be757879fc3)
The attacker has to frontrun it only once, in order to cancel all the requests.

**Comment by IlIlHunterlIlI** [comment]
I saw this statement in discord and it seems that depositing whole balance is a problem and not a wanted behavior from sponsor. I think the issue here clearly violating the hierarchy of truth.

> Tokens he just deposited

https://discord.com/channels/812037309376495636/1252276613417013353/1255474866396594217

**Comment by 10xhash** [comment]
> I see that the DOS is not mentioned anywhere, but as I see in both scenarios, the impact of the attack is that either `emergencyWithdraw` or `processsWithdrawals` will fail. That's what I meant by DOS, the attacker in that case would DOS the withdrawal call. But, as I understand the withdrawal call can be repeated in the very next block and would succeed if the attacker doesn't attack again, correct?
> 
> > griefing of withdrawals, excessive gas consumption for the Vault operators
> 
> And to clarify the impact in the report, you mean the Vault operators would have excessive gas consumptions, because they would have execute withdrawals several times before they're executed sucessfully?

For DefaultBondStrategy, the assets are never left idle in the vault intentionally. All assets are deposited into respective strategies with every deposit. And when withdrawing, all assets are withdrawn from the strategies before processing the user's withdrawals (which is not being mentioned here). And as soon as the withdrawal is finished, the assets are deposited back to the respective strategies

https://github.com/sherlock-audit/2024-06-mellow/blob/26aa0445ec405a4ad637bddeeedec4efe1eba8d2/mellow-lrt/src/strategies/DefaultBondStrategy.sol#L96-L121
```solidity
    function _processWithdrawals(address[] memory users) private {
        if (users.length == 0) return;


        address[] memory tokens = vault.underlyingTokens();
        for (uint256 index = 0; index < tokens.length; index++) {
            bytes memory data_ = tokenToData[tokens[index]];
            if (data_.length == 0) continue;
            Data[] memory data = abi.decode(data_, (Data[]));
            for (uint256 i = 0; i < data.length; i++) {
                uint256 amount = IERC20(data[i].bond).balanceOf(address(vault));
                if (amount == 0) continue;
                vault.delegateCall(
                    address(bondModule),
                    abi.encodeWithSelector(
                        IDefaultBondModule.withdraw.selector,
                        data[i].bond,
                        amount
                    )
                );
            }
        }


        vault.processWithdrawals(users);
        _deposit();
        emit DefaultBondStrategyProcessWithdrawals(users, block.timestamp);
    }
```

**Comment by WangSecurity** [comment]
@10xhash thank you for that remark, but as I understand the problem we discuss here is in Vault::processWithdrawals. 

So, if we process withdrawals via `DefaultBondStrategy`, then the funds are firstly withdrawn from the Vault and then, if there are any deposit requests that cannot be satisfied, they're deposited back into vault. Correct?

Now about this comment @blckhv :
> No, I mislead you with my first comment and I'm sorry about the confusion, the withdrawal call can't be repeated in the very next block, because as we mentioned [isProcessingPossible](https://github.com/mellow-finance/mellow-lrt/blob/dev-symbiotic-deploy/src/Vault.sol#L554) will evaluate to false and will cancel all the request, each user will have to resubmit his request again. Also, the operator is mentioned to be an automation bot, configured to execute withdrawals once in a while:

But as I see, the `isProcessingPossible` and `isWithdrawalPossible` are done on each individual withdrawal request, and if they fail for one request, they will process all the other withdrawals, since they call continue, which afaik means they finish that one for-loop and start with the next one, no? Could you please clarify if my understanding is incorrect here and indeed it will cancel all the withdrawals not only one. Or you mean every withdrawal request will be canceled individually, again excuse me for misunderstanding.

And based on the above comment, there are now idle tokens, so the report is incorrect and this issue won't happen? Excuse me if I misunderstand how the protocol work, but please correct me.

**Comment by blckhv** [comment]
> Or you mean every withdrawal request will be canceled individually, again excuse me for misunderstanding.

Yes, since [`underlyingTVL`](https://github.com/mellow-finance/mellow-lrt/blob/dev-symbiotic-deploy/src/Vault.sol#L512) returns 0 balance of the Vault, all the requests will be canceled [here](https://github.com/mellow-finance/mellow-lrt/blob/dev-symbiotic-deploy/src/Vault.sol#L553-L554) or for the requests that specified [`minAmount`](https://github.com/mellow-finance/mellow-lrt/blob/dev-symbiotic-deploy/src/Vault.sol#L496) = 0, their LP tokens will be burned, without transferring them any collateral back.

**Comment by 10xhash** [comment]
> So, if we process withdrawals via DefaultBondStrategy, then the funds are firstly withdrawn from the Vault and then, if there are any deposit requests that cannot be satisfied, they're deposited back into vault. Correct?

I can't understand your statement fully

Firstly funds are withdrawn from the different contracts (ie. strategy/bond contracts) to which they were deposited. Now all the tokens will be present in the vault. Then all the withdrawals are processed. After this all the tokens are redeposited back to the earlier contracts itself

https://github.com/sherlock-audit/2024-06-mellow/blob/26aa0445ec405a4ad637bddeeedec4efe1eba8d2/mellow-lrt/src/strategies/DefaultBondStrategy.sol#L90-L121
```solidity
    function processWithdrawals(address[] memory users) external {
        if (users.length == 0) return;
        _requireAtLeastOperator();
        _processWithdrawals(users);
    }


    function _processWithdrawals(address[] memory users) private {
        if (users.length == 0) return;


        address[] memory tokens = vault.underlyingTokens();
        for (uint256 index = 0; index < tokens.length; index++) {
            bytes memory data_ = tokenToData[tokens[index]];
            if (data_.length == 0) continue;
            Data[] memory data = abi.decode(data_, (Data[]));
            for (uint256 i = 0; i < data.length; i++) {
                uint256 amount = IERC20(data[i].bond).balanceOf(address(vault));
                if (amount == 0) continue;
                vault.delegateCall(
                    address(bondModule),
                    abi.encodeWithSelector(
                        IDefaultBondModule.withdraw.selector,
                        data[i].bond,
                        amount
                    )
                );
            }
        }


        vault.processWithdrawals(users);
        _deposit();
        emit DefaultBondStrategyProcessWithdrawals(users, block.timestamp);
    }
```

**Comment by 0xHuntoor** [comment]
Operator is trusted and should be able to call the correct function when needed

`DefaultBondStrategy` process withdrawals eventually calls process withdrawals in the vault and there would be no problem like hash said

**Comment by blckhv** [comment]
you're assuming the scenario when Vault has a `DefaultBondStrategy` fully functional and ready to handle each Vault deposit, but this is not the case - [Symbiotic](https://app.symbiotic.fi/restake/) currently can't handle more deposits and this will leave funds idling in the Vault, for a moment, but since withdrawals are instant this opens window for the Vault to deposit, but we have no exact order of operations that the Operator will perform? 
He can either deposit the funds or execute withdrawals. On the other hand the possible actions of the user in this situation are clear - he can only deposit and that deposit will [transfer that much tokens](https://github.com/sherlock-audit/2024-06-mellow/blob/26aa0445ec405a4ad637bddeeedec4efe1eba8d2/mellow-lrt/src/modules/symbiotic/DefaultBondModule.sol#L16-L19) or the entire Vault balance in case there is enough buffer, which can only **decrease or even zero (which has the maximal impact as explained in the report)** the [`underlyingTVL`](https://github.com/sherlock-audit/2024-06-mellow/blob/26aa0445ec405a4ad637bddeeedec4efe1eba8d2/mellow-lrt/src/Vault.sol#L112-L119) since it calculates only **Vault balance** and not the strategy allocated balance.

Vs. the scenario when `DepositCallback` only deposits the newly added tokens, which is how the [`IDepositCallback`](https://github.com/sherlock-audit/2024-06-mellow/blob/26aa0445ec405a4ad637bddeeedec4efe1eba8d2/mellow-lrt/src/interfaces/utils/IDepositCallback.sol#L11) initially was created:
- Tokens that are **idling** in the Vault remain untouched, they can still be deposited by a TRUSTED operator, or be used to satisfy the withdrawal requests.
- Tokens that the user has deposited are tried to be staked in Symbiotic if there is enough limit or if not - they stay in the Vault until there is a satisfactory limit so the Operator can process them

**Comment by WangSecurity** [comment]
Firstly, as I understand there's no loss of funds. Secondly, the largest impact is that the user will have to request the withdrawal again and wait for the operator to process it. Thirdly, the withdrawals can be processed through strategies contracts and it wouldn't lead to these problems (as I understand in both, `SimpleDVTStakingStrategy` and `DefaultBondStrategy`) even if the entire vault TVL is deposited into strategies.

Hence, there's the way that the withdrawals can be done without an issue, but even if the withdrawals are processed via vault directly, I believe the following rule applies:

> Griefing for gas (frontrunning a transaction to fail, even if can be done perpetually) is considered a DoS of a single block, hence only if the function is clearly time-sensitive, it can be a Medium severity issue

And I believe the functions that will fail in that case are not time-sensitive (I understand that `processWithdrawals` won't fail per se and these are the deposits, that will fail).

Hence, I believe the report should remain invalid, planning to reject the escalation.

**Comment by Slavchew** [comment]
Yes, you're right, I observed the report again and indeed the user can only permanently block withdrawals if the operator keeps calling `Vault:processWithdrawals`, but a call to `DefaultBondStrategy.processWithdrawals` will remove the possibility of permanent grief by the user.

You can reject the escalation and leave it invalid.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0x3b33](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/208/#issuecomment-2231792844): rejected
