### ISSUE TITLE
eeyore - The delay time for emergency withdrawals can be extended for withdrawal requests that are already pending

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-mellow-judging#218]
eeyore

Medium

# The delay time for emergency withdrawals can be extended for withdrawal requests that are already pending

## Summary

The emergency withdrawal delay time for pending withdrawals is not stored during the creation of a withdrawal request and is dependent on the `configurator.emergencyWithdrawalDelay()` value, which can be changed/extended.

## Vulnerability Detail

When a withdrawal request is created, an unwritten agreement is made between the user and the protocol that the protocol will process the request swiftly or that the user will be able to perform an emergency withdrawal after a set time. 

However, if the `configurator.emergencyWithdrawalDelay()` is increased, all pending withdrawal requests are affected. Only actions in favor of the users, such as a decrease in delay time, should be acceptable.

## Impact

The user's emergency withdrawal delay can be extended from the expected X days to a maximum of 365 days.

## Code Snippet

https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L389-L392

## Tool used

Manual Review

## Recommendation

Store the withdrawal delay timestamp in the withdrawal request. Additionally, if `configurator.emergencyWithdrawalDelay()` is decreased in favor of the user, compare it accordingly.

```diff
        if (
+           request.withdrawalTimestamp > timestamp &&
            request.timestamp + configurator.emergencyWithdrawalDelay() >
            timestamp
        ) revert InvalidState();
```

This ensures that the delay time for pending withdrawals is not subject to unexpected changes, protecting the user's ability to perform an emergency withdrawal as initially agreed.

**Comment by 0xklapouchy** [comment]
@z3s 

There is definitely an opportunity loss for a user if the withdrawal is delayed. The user expects that their withdrawal will be processed without delay, or at worst, within a specified delay period (X). However, with the current approach, the withdrawal delay can be X + Y, leading to an opportunity loss as the user cannot manage their own funds effectively.

In addition user can be denied the withdrawal in case he sets his request.deadline to the timestamp right after his expected withdrawal delay. In a situation when the `configurator.emergencyWithdrawalDelay()` will be increased his withdrawal request will be cancelled:

```
        if (timestamp > request.deadline) {
            _cancelWithdrawalRequest(sender);
            return actualAmounts;
        }
```
