### ISSUE TITLE
Angry_Mustache_Man - Wrong function used by `WStethRatiosAggregatorV3.sol`

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-mellow-judging#228]
Angry_Mustache_Man

High

# Wrong function used by `WStethRatiosAggregatorV3.sol`

## Summary
`WStethRatiosAggregatorV3.sol` is used to calculate the price of WstEth . Here in this contract it is intended to calculate the price of wstEth for 1 stEth i.e., price of the ratio wstEth/stEth , but it uses wrong function from Lido to do the same . Protocol should be using `getWstETHByStETH()` instead of `getStETHByWstETH()`
## Vulnerability Detail
The Aggregator for finding the price of wstEth uses wrong function from Lido as can be seen here : 
https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/oracles/WStethRatiosAggregatorV3.sol#L15C3-L17C6
```solidity
 function getAnswer() public view returns (int256) {
        return int256(IWSteth(wsteth).getStETHByWstETH(10 ** decimals));
    }
```
As for calculating `wstEth/stEth` -  which is amount of wstETH for a given amount of stETH we need to use `getWstETHByStETH()` instead of `getStETHByWstETH()` as explained in the [Lido docs](https://docs.lido.fi/contracts/wsteth#getwstethbysteth)
This leads to using wrong price whenever wstEth:stEth != 1:1 which is the case in most of times ( prices of [wstEth]() & [stEth]) (Presently the wstEth/stEth = 0.85 & stEth/wstEth = 1.17 )

## Impact
Due to this the entire deposit & withdrawal miscalculates the `depositValue` of User & `totalValue` of Vault as shown below : 
https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L321C2-L336C10
```solidity
IPriceOracle priceOracle = IPriceOracle(configurator.priceOracle());
        for (uint256 i = 0; i < tokens.length; i++) {
            uint256 priceX96 = priceOracle.priceX96(address(this), tokens[i]);                <@audit
            totalValue += totalAmounts[i] == 0
                ? 0
                : FullMath.mulDivRoundingUp(totalAmounts[i], priceX96, Q96);                 <@audit
            if (ratiosX96[i] == 0) continue;
            uint256 amount = FullMath.mulDiv(ratioX96, ratiosX96[i], Q96);
            IERC20(tokens[i]).safeTransferFrom(
                msg.sender,
                address(this),
                amount
            );
            actualAmounts[i] = amount;
            depositValue += FullMath.mulDiv(amount, priceX96, Q96);                             <@audit
        }
```
&& 
https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L526C6-L532C10
```solidity
   IPriceOracle priceOracle = IPriceOracle(configurator.priceOracle());
        for (uint256 i = 0; i < tokens.length; i++) {
            uint256 priceX96 = priceOracle.priceX96(address(this), tokens[i]);             <@audit
            s.totalValue += FullMath.mulDiv(amounts[i], priceX96, Q96);                      <@audit
            s.ratiosX96Value += FullMath.mulDiv(s.ratiosX96[i], priceX96, Q96);            <@audit
            s.erc20Balances[i] = IERC20(tokens[i]).balanceOf(address(this));
        }
```
This causes inflation of values and miscalculation in the Vault . 
## Code Snippet
https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/oracles/WStethRatiosAggregatorV3.sol#L15C3-L17C6

https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L321C2-L336C10

https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L526C6-L532C10

## Tool used

Manual Review , Lido Docs

## Recommendation
Change the function used to `getWstETHByStETH()`

**Comment by WangSecurity** [comment]
As the reporter said [here](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/29#issuecomment-2228677657), this issue is invalid.
