### ISSUE TITLE
eeyore - Unable to use stETH directly in DepositWrapper contract do to the Lido 1-2 wei corner case

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-mellow-judging#234]
eeyore

Medium

# Unable to use stETH directly in DepositWrapper contract do to the Lido 1-2 wei corner case

## Summary

There are many cases when 1-2 wei is left behind when transferring stETH via the safeTransferFrom() function. This can be checked [here](https://docs.lido.fi/guides/lido-tokens-integration-guide/#1-2-wei-corner-case).

## Vulnerability Detail

When users call the deposit() function with the amount parameter, that amount is passed down in the call chain, and the actual amount of stETH transferred from the user is not rechecked.

## Impact

The deposit() function will not work correctly with the stETH token directly.

## Code Snippet

https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/utils/DepositWrapper.sol#L56-L57

## Tool used

Manual Review

## Recommendation

Similar to fee-on-transfer tokens, in the case of the stETH token, compare the amount value with the balanceBefore and balanceAfter of stETH done after the safeTransferFrom() call.

Duplicate of #299

**Comment by 0xklapouchy** [comment]
@z3s 

This is a valid issue, correctly pointing out that when stETH is used directly (token == stETH), the deposit() function will always revert.

```
        if (token == steth) {
            IERC20(steth).safeTransferFrom(sender, wrapper, amount); // @audit-issue - M - Lido: 1-2 wei corner case
            amount = _stethToWsteth(amount);
        } else if (token == weth) {
```

This is an edge case, but in such a case, the function is permanently broken.
