### ISSUE TITLE
0xBhumii - Incorrect Oracle Data Handling in `setChainlinkOracles` Function

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-mellow-judging#245]
0xBhumii

Medium

# Incorrect Oracle Data Handling in `setChainlinkOracles` Function

## Summary
The `setChainlinkOracles` function in the `ChainlinkOracle` contract has an inconsistency in handling zero address oracles (`aggregatorV3`). The function skips validation for these entries but assigns them in the subsequent loop, potentially storing invalid oracle data. This can lead to incorrect price calculations and unexpected contract behavior.

## Vulnerability Detail
The `setChainlinkOracles` function processes two arrays of equal length: `tokens` and `data_`. The first loop checks if `data_[i].aggregatorV3` is a zero address and skips validation for these entries using `continue`. However, the second loop assigns all entries from `data_` to the `_aggregatorsData` mapping, including those with zero addresses.
i.e 1. The first loop skips entries with zero addresses, effectively excluding them from validation.
2. The second loop assigns all entries, including those with zero addresses, to the `_aggregatorsData` mapping.

## Impact
Relying on invalid oracle data can lead to incorrect behavior in vault functionalities that depend on accurate price information.

## Code Snippet

https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/oracles/ChainlinkOracle.sol#L46

```solidity
function setChainlinkOracles(
    address vault,
    address[] calldata tokens,
    AggregatorData[] calldata data_
) external {
    IDefaultAccessControl(vault).requireAdmin(msg.sender);
    if (tokens.length != data_.length) revert InvalidLength();
    for (uint256 i = 0; i < tokens.length; i++) {
        if (data_[i].aggregatorV3 == address(0)) continue;
        _validateAndGetPrice(data_[i]);
    }
    for (uint256 i = 0; i < tokens.length; i++) {
        _aggregatorsData[vault][tokens[i]] = data_[i];
    }
    emit ChainlinkOracleSetChainlinkOracles(
        vault,
        tokens,
        data_,
        block.timestamp
    );
}
```

## Tool used

Manual Review

## Recommendation

To ensure only validated data is assigned, modify the second loop to skip entries with a zero address:

```solidity
function setChainlinkOracles(
    address vault,
    address[] calldata tokens,
    AggregatorData[] calldata data_
) external {
    IDefaultAccessControl(vault).requireAdmin(msg.sender);
    if (tokens.length != data_.length) revert InvalidLength();
    for (uint256 i = 0; i < tokens.length; i++) {
        if (data_[i].aggregatorV3 == address(0)) continue;
        _validateAndGetPrice(data_[i]);
    }
    for (uint256 i = 0; i < tokens.length; i++) {
        if (data_[i].aggregatorV3 == address(0)) continue; // Skip zero address entries
        _aggregatorsData[vault][tokens[i]] = data_[i];
    }
    emit ChainlinkOracleSetChainlinkOracles(
        vault,
        tokens,
        data_,
        block.timestamp
    );
}
```

This change ensures that only entries with valid `aggregatorV3` addresses are stored, maintaining the integrity of the oracle data.

**Comment by recursiveEth** [comment]
Escalate
 it's a valid issue because it iterates over the tokens array, skipping entries where data_[i].aggregatorV3 is address(0) and validating the rest, check the vulnerability details again.
Even though it's a admin function there is mistake in code, they have prior check for zero aggregator address which means they have additional check and adding the same address 0 in next statement is code mistake as there the whole segment of code dedicated to handling such paths it doesn't depend of admin please have a look carefully, thank you

**Comment by sherlock-admin3** [comment]
> Escalate
>  it's a valid issue because it iterates over the tokens array, skipping entries where data_[i].aggregatorV3 is address(0) and validating the rest, check the vulnerability details again.
> Even though it's a admin function there is mistake in code, they have prior check for zero aggregator address which means they have additional check and adding the same address 0 in next statement is code mistake as there the whole segment of code dedicated to handling such paths it doesn't depend of admin please have a look carefully, thank you

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by z3s** [comment]
#173

**Comment by WangSecurity** [comment]
> Relying on invalid oracle data can lead to incorrect behavior in vault functionalities that depend on accurate price information

I don't understand the impact, what incorrect behaviour it will cause? The report shows the root cause, 0 address chainlink price feed is saved, but it doesn't identify an impact.

**Comment by WangSecurity** [comment]
Since no additional information is provided, planning to reject the escalation and leave the issue as it is.

**Comment by recursiveEth** [comment]
@WangSecurity 

i am not saying about that admin is malicious or by choice they will enter the wrong values, the things they didn't handle the case properly if they are checking for the possible scenarios in one statement they should have done that in next for loop also but they are inserting the wrong values in the mapping admin role cannot cover this issue its the wrong code to implement the function, if admin could do all the things properly then there will never be requirement of basic address(0) check globally, and they didn't implement properly whole price fetch mechanism will make output wrong value you can direct to https://github.com/sherlock-audit/2024-06-mellow-judging/issues/246 for more detail for this issue how can this impact, i request you to check out the vulnerability once again, thank you

**Comment by WangSecurity** [comment]
Thank you for referencing another report, but in that case I believe the admin is responsible for adding a token with existing chainlink oracle and this issue falls under the zero address check and admin input validation rules.

The decision remains the same, reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [recursiveEth](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/245/#issuecomment-2231124556): rejected
