### ISSUE TITLE
Audinarey - staged data can be delayed for more than `MAX_DELAY` period of 365 days

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-mellow-judging#249]
Audinarey

High

# staged data can be delayed for more than `MAX_DELAY` period of 365 days

## Summary
The `MAX_DELAY` is the _maximum allowed delay for any staged data_ as shown below. 
The protocol is designed such that, to change a vault configuration variable, the new value is first staged for a period of time not exceeding `MAX_DELAY` which is currently hardcoded to 365 days.

At the point of staging, the `s.stageTimestamp` is cached (as seen on `L58`) and this is used to determine whether or not the staged changed can be committed when commit is called as seen on `L69`. If the staging delay period has elapsed, the value is then committed to state in `L76`

```solidity
File: IVaultConfigurator.sol

49: @>   /// @notice Returns the maximum allowed delay for any staged data.
50: @>  /// @return uint256 The constant `MAX_DELAY` indicating the maximum delay period (365 days).
51:     function MAX_DELAY() external pure returns (uint256);
52: 

File: VaultConfigurator.sol
09:     /// @inheritdoc IVaultConfigurator
10: @>  uint256 public constant MAX_DELAY = 365 days; // the maximum allowed delay for any staged data.
11:     /// @inheritdoc IVaultConfigurator
12: @>  uint256 public constant MAX_WITHDRAWAL_FEE = 5e7; // 5%


56:     function _stage(Data storage s, uint256 value) private {
57:         s.stageTimestamp = block.timestamp;
58: @>      s.stagedValue = value;
59:         bytes32 slot;
60:         assembly {
61:             slot := s.slot
62:         }
63:         emit Stage(slot, s, value, block.timestamp);
64:     }


66:     function _commit(Data storage s, Data storage delay) private { // (staged, current)
67:         uint256 timestamp = s.stageTimestamp;
68:         if (timestamp == 0) revert InvalidTimestamp();
69: @>      if (block.timestamp - timestamp < delay.value)
70:             revert InvalidTimestamp();
....
75:         emit Commit(slot, s, block.timestamp);
76: @>      s.value = s.stagedValue;
77:         delete s.stageTimestamp;
78:         delete s.stagedValue;
79:     }

```

On `L69` there is a check to ensure the staged value is not committed prematurely. The problem is that the check is done against the current value of the  particular vault configuration variable to be committed and this value can be higher than the `MAX_DELAY` value because some config values like `_withdrawalCallback.value` is of type `uint160` and it can uncontrollably be way above 365days (31536000 seconds) as it is derived from an `address`.

Even the `MAX_WITHDRAWAL_FEE = 5e7`  (5%) is greater than `MAX_DELAY`
<img width="293" alt="Screenshot 2024-06-27 at 13 43 32" src="https://github.com/sherlock-audit/2024-06-mellow-Audinarey/assets/131544007/a65a74d5-db86-4359-98e8-0034b6597629">

Even a 3.2% withdrawal fee is greater than the `MAX_DELAY` of 365 days as shown below in `chisel`

```solidity
➜ 4e7 > 365 days
Type: bool
└ Value: true
➜ 3.5e7 > 365 days
Type: bool
└ Value: true
➜ 3.2e7 > 365 days
Type: bool
└ Value: true
➜ 
```
## Vulnerability Detail

- the current value of `_withdrawalFeeD9` is  4e7 (4%)
- admin decides to change the `_withdrawalFeeD9` to say 4.5 % (or any other value below `MAX_WITHDRAWAL_FEE` )
- the new value is staged
- when commit is called after some time (say after 365 days), it will check if the appropriate delay has elapsed, but as shown below `L69` will revert until 520 days has elapsed as against a maximum of 365 days
```solidity
➜ 4.5e7 > 365 days
Type: bool
└ Value: true

➜ 4.5e7 - 365 days = 13464000

➜ 13464000 / 86400 == 155 days

➜ 365 days + 155 days == 520 days
```

## Impact
staged data can be delayed for more than `MAX_DELAY` period 
- causing a denial of service because values cannot be successfully committed within the `MAX_DELAY` period
- breaking core protocol functionality

## Code Snippet
https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/VaultConfigurator.sol#L9-L12

https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/VaultConfigurator.sol#L69

https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/VaultConfigurator.sol#L261-L266

## Tool used

Manual Review

## Recommendation
Modify the `_commit(...)` function to use `_baseDelay.value` for staging delay checks

```solidity
66:     function _commit(Data storage s, Data storage delay) private {
67:         uint256 timestamp = s.stageTimestamp;
68:         if (timestamp == 0) revert InvalidTimestamp();

69:  -      if (block.timestamp - timestamp < delay.value)
69:  +     if (block.timestamp - timestamp < _baseDelay.value)

70:             revert InvalidTimestamp();
....
75:         emit Commit(slot, s, block.timestamp);
76:         s.value = s.stagedValue;
77:         delete s.stageTimestamp;
78:         delete s.stagedValue;
79:     }
```

**Comment by Audinarey** [comment]
Escalate


The check is done against an abysmal value which is above the  `MAX_DELAY` period and this breaks accounting and core protocol functionality of the `VaultConfigurator` contract

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> 
> The check is done against an abysmal value which is above the  `MAX_DELAY` period and this breaks accounting and core protocol functionality of the `VaultConfigurator` contract

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by Audinarey** [comment]
@z3s  @WangSecurity kindly review 

The check is done against an abysmal value which is above the `MAX_DELAY` period and this breaks accounting and core protocol functionality of the VaultConfigurator contract as some values cannot be committed from staging even after 365days (some go as high as 520 days as explained in the finding.

**Comment by z3s** [comment]
In Code Snippet you linked [stageWithdrawalFeeD9](https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/VaultConfigurator.sol#L261-L266) function.
[commitWithdrawalFeeD9](https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/VaultConfigurator.sol#L269-L271) uses `_withdrawalFeeD9Delay` as delay.
`_withdrawalFeeD9Delay` staged [here](https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/VaultConfigurator.sol#L359-L364). and there is a check to not exceed `MAX_DELAY`.
I can't understand the problem you report!?
