### ISSUE TITLE
StraawHaat - `convertAndDeposit()` function is unusable for users

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-mellow-judging#251]
StraawHaat

Medium

# `convertAndDeposit()` function is unusable for users

## Summary

`convertAndDeposit()` function is unusable for users. This is because the function calls `vault.delegateCall()` which has a check if the caller is admin or operator. 

## Vulnerability Detail

The `convertAndDeposit` function in the `SimpleDVTStakingStrategy.sol` converts a specified amount of WETH into WSTETH. 

```solidity
    function convertAndDeposit(
        uint256 amount,
        uint256 blockNumber,
        bytes32 blockHash,
        bytes32 depositRoot,
        uint256 nonce,
        bytes calldata depositCalldata,
        IDepositSecurityModule.Signature[] calldata sortedGuardianSignatures
    ) external returns (bool success) {
        (success, ) = vault.delegateCall(
            address(stakingModule),
            abi.encodeWithSelector(
                IStakingModule.convertAndDeposit.selector,
                amount,
                blockNumber,
                blockHash,
                depositRoot,
                nonce,
                depositCalldata,
                sortedGuardianSignatures
            )
        );
        emit ConvertAndDeposit(success, msg.sender);
    }
```

From the interface of the function, we can see that it should be callable by any user:

```solidity
     * @notice The function can be called by anyone.
     */
    function convertAndDeposit(
        uint256 amount,
        uint256 blockNumber,
        bytes32 blockHash,
        bytes32 depositRoot,
        uint256 nonce,
        bytes calldata depositCalldata,
        IDepositSecurityModule.Signature[] calldata sortedGuardianSignatures
    ) external returns (bool success);
```

> The function can be called by anyone.

But this is not true because the function calls `vault.delegateCall()`, which has check whether the caller is an admin or an operator:

```solidity
    function delegateCall(
        address to,
        bytes calldata data
    ) external returns (bool success, bytes memory response) {
        _requireAtLeastOperator();
  ............
```

```solidity
    function _requireAtLeastOperator(address sender) internal view {
        if (!isAdmin(sender) && !isOperator(sender)) revert Forbidden();
    }
```

This means that the function is unusable by users.
## Impact

Тhe function is unusable by users. 

According to Sherlock [rules](https://docs.sherlock.xyz/audits/judging/judging#iii.-sherlocks-standards), this means Medium severity for two reasons:

First:
> How to identify a medium issue:
> - Breaks **core** contract functionality

Second: CODE COMMENTS is a source of truth. 
> If the protocol team provides specific information in the README or CODE COMMENTS, that information stands above all judging rules.
## Code Snippet

https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/strategies/SimpleDVTStakingStrategy.sol#L36-L59
https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/interfaces/strategies/ISimpleDVTStakingStrategy.sol#L49
https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L253

## Tool used

Manual Review

## Recommendation

Make the function usable by users.

**Comment by StraawHaat** [comment]
Escalate

This issue shows how users cannot use the `convertAndDeposit()` function because of the `_requireAtLeastOperator();` check in `delegateCall()`. This breaks core contract functionality, which is a valid Medium.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This issue shows how users cannot use the `convertAndDeposit()` function because of the `_requireAtLeastOperator();` check in `delegateCall()`. This breaks core contract functionality, which is a valid Medium.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Firstly, let's use the complete definition of severities, not a part of them:
> Breaks core contract functionality, **rendering the contract useless or leading to loss of funds.**

Secondly, this rule applies here:
>The judge can decide that CODE COMMENTS are outdated based on contextual evidence. In that case, the judging guidelines are the chosen source of truth.
> > Example: The code comments state that "a swap can never fail" even though the code is built to support failing swaps.

I believe the comment is outdated and just breaking the core contract functionality is not medium itself, it has to have a broader impact (as said in the definition of medium severity), which is missing here. Plan to reject the escalation, leaving the issue as it is.

**Comment by StraawHaat** [comment]
If the comment is outdated and the `convertAndDeposit()` function should not be used by normal users but only by the operator or admin, then I agree that this issue is invalid.

However, if this function is supposed to be used by normal users, then this issue is valid because the core function does not work.

**Comment by InfectedIsm** [comment]
I think that there is a mistake in this report.
`SimpleDVTStakingStrategy::convertAndDeposit` has no role permission, so it can be called by anyone.
Then, as the author shown, there is a call to [`vault.delegateCall`](https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L267).
This call is not a `delegatecall` yet, its an external call to vault.
This means in the context of `Vault`, `msg.sender` is `SimpleDVTStakingStrategy` and not the original caller.
So, `_requireAtLeastOperator` is checked against `SimpleDVTStakingStrategy` address, which is a a protocol owned contract.

**Comment by WangSecurity** [comment]
@InfectedIsm thank for that great remark, is `SimpleDVTStakingStrategy` represent an operator or an admin of `Vault` in that case? I assume so, but want to get a confirmation.

**Comment by InfectedIsm** [comment]
@WangSecurity there is no explicit reference about `SimpleDVTStakingStrategy` being an operator or an admin
But if you consider protocol admins trusted and doing things right, they will configure `SimpleDVTStakingStrategy` such as it is able to call `Vault::convertandDeposit`, otherwise `SimpleDVTStakingStrategy::convertAndDeposit` will always revert as this is the only call it executes.
So, what would prevent users to not being able to call the function is if admins do not configure the role access of `SimpleDVTStakingStrategy` correctly.

We could also reference [the documentation](https://docs.mellow.finance/mellow-lrt-primitive/lrt-contracts/strategies/simpledvtstakingstrategy#overview): 
> The SimpleDVTStakingStrategy contract manages staking operations by interacting with a staking module and vault

**Comment by WangSecurity** [comment]
I agree with the above comment. For this issue to occur the trusted admin needs to not set `SimpleDVTStakingStrategy` as the operator or an admin in Vault, which I believe would be a mistake.

Planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [StraawHaat](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/251/#issuecomment-2231524859): rejected
