### ISSUE TITLE
hash - DOS on Obol deposits due to frontrunning

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-mellow-judging#265]
hash

Medium

# DOS on Obol deposits due to frontrunning

## Vulnerability Detail
For obol staking associated vaults, the `weth` in the Vault is supposed to be allocated to the obol validators by invoking the `convertAndDeposit` function

[link](https://github.com/sherlock-audit/2024-06-mellow/blob/26aa0445ec405a4ad637bddeeedec4efe1eba8d2/mellow-lrt/src/strategies/SimpleDVTStakingStrategy.sol#L36-L44)
```solidity
    function convertAndDeposit(
        uint256 amount,
        uint256 blockNumber,
        bytes32 blockHash,
        bytes32 depositRoot,
        uint256 nonce,
        bytes calldata depositCalldata,
        IDepositSecurityModule.Signature[] calldata sortedGuardianSignatures
    ) external returns (bool success) {
```

Since any user can permissionlessly invoke the `depositBufferedEther` function of Lido given they have these params, a user can front run this call and invoke the `depositBufferedEther` function directly. This will cause the deposit to occur without the assets in the vault being allocated and the second call to revert since the depositRoot would change due to the new deposit. 

## Impact
DOS on vault deposits for obol staking vaults

## Tool used
Manual Review

## Recommendation
Use private txs / high gas fees

**Comment by 10xhash** [comment]
> > DoS has two separate scores on which it can become an issue:
> > 
> > 1. The issue causes locking of funds for users for more than a week.
> > 2. The issue impacts the availability of time-sensitive functions
> 
> `convertAndDeposit` can be used with high gas or with flashbots to mitigate this problem. Issue is valid Low/Info.

Escalate

Lido's depositor bot (used to invoke this contract) has been invoking the depositBufferedEther function as a normal transaction majority of the time (eg; https://mempool.guru/tx/0x1c47bb9a9b766505e468d418d43a830ff3b28c7466558a7dc8e1cf62645d6c9c). This is acceptable for Lido under the assumption `the change in deposit root of the beacon contract occurs rarely` and a front-run there would require a deposit to the beacon chain. With mellow there is an additional possibility of user's to cause DOS by using these parameters directly on the deposit security module of lido without having to make any deposit to beacon chain themselves

**Comment by sherlock-admin3** [comment]
> > > DoS has two separate scores on which it can become an issue:
> > > 
> > > 1. The issue causes locking of funds for users for more than a week.
> > > 2. The issue impacts the availability of time-sensitive functions
> > 
> > `convertAndDeposit` can be used with high gas or with flashbots to mitigate this problem. Issue is valid Low/Info.
> 
> Escalate
> 
> Lido's depositor bot (used to invoke this contract) has been invoking the depositBufferedEther function as a normal transaction majority of the time (eg; https://mempool.guru/tx/0x1c47bb9a9b766505e468d418d43a830ff3b28c7466558a7dc8e1cf62645d6c9c). This is acceptable for Lido under the assumption `the change in deposit root of the beacon contract occurs rarely` and a front-run there would require a deposit to the beacon chain. With mellow there is an additional possibility of user's to cause DOS by using these parameters directly on the deposit security module of lido without having to make any deposit to beacon chain themselves

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
I'm not sure I understand the impact here:

> DOS on vault deposits for obol staking vaults

But as I understand from the report, the funds are not lost and the deposit can be done in the next bloc, or can you elaborate on it?

**Comment by 10xhash** [comment]
> I'm not sure I understand the impact here:
> 
> > DOS on vault deposits for obol staking vaults
> 
> But as I understand from the report, the funds are not lost and the deposit can be done in the next bloc, or can you elaborate on it?

The amount in mellow is not lost. Using this strategy to deposit (if not done via private txs) allows a user to always expire these params (depositRoot, nonce, sortedGuardianSignatures etc) by invoking lido's deposit function directly with these params at no extra cost (unlike front running lido which requires depositing eth into beacon chain etc.), thereby disallowing mellow to deposit it's funds into obol. In case a deposit is made once, new params will have to be generated and a min block period will have to pass (currently 25) after which the deposit can be tried again

_(An additional note: It was mentioned in lido discord that they are intending to use private mempools with public mempools as a fallback and it was due to an issue with bot's signing that currently the private tx's send were getting discarded. But if we look at the depositor bot txs it is predominantly using public mempools since the starting and the official forum post mentions usage of higher gas fees if needed inorder to minimize the probability of the deposit contract data root changes)_

**Comment by 0xHuntoor** [comment]
25 block * 12 second (average blockTime) < 7 days DOS

**Comment by WangSecurity** [comment]
Since it doesn't lead to a loss of funds and the DOS is 25 blocks, and the functionality is not time-sensitive, I believe it doesn't qualify for medium severity and DOS requirements. Planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [10xhash](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/265/#issuecomment-2231646520): rejected
