### ISSUE TITLE
WildSniper - The `deposit()` function in the `DepositWrapper` will revert on multiple instances in some edge cases with potential loss of funds

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-mellow-judging#281]
WildSniper

High

# The `deposit()` function in the `DepositWrapper` will revert on multiple instances in some edge cases with potential loss of funds

## Summary

The `deposit()` function in the `DepositWrapper` contract is designed to simplify the process of converting tokens like ETH, wETH, and wstETH into wstETH for depositing into the Vault. However, there is an issue with the way it handles the conversion of ETH and wETH to wstETH, which can lead to multiple reverts and potential fund loss.

## Vulnerability Detail

The `deposit()` function in the `DepositWrapper` contract allows users to deposit ETH, wETH, stETH, or wstETH into the Vault. When the user deposits ETH or wETH, the function attempts to convert these tokens to wstETH using the `_ethToWsteth()` and `_wethToWsteth()` functions, respectively.

The problem lies in the assumption that the conversion from ETH to stETH (and subsequently to wstETH) maintains a 1:1 ratio. However, according to the Lido documentation, this assumption is not always true, and in rare cases, the ratio may decrease or increase

The `_ethToWsteth()` function submits the provided ETH amount to the Lido stETH contract and assumes that the returned stETH amount is equal to the submitted ETH amount. However, if the conversion ratio is not 1:1, the actual stETH balance received may be lower than the submitted ETH amount.

Similarly, the `_wethToWsteth()` function assumes a 1:1 conversion ratio when withdrawing ETH from wETH and submitting it to the Lido stETH contract.

## Impact

impact would be high, 
- cause if the ration increases then the extra `stETH` will be permenantly freezed
- if the ratio decreases reverts will happen during `wrapping`

## Code Snippet

https://github.com/sherlock-audit/2024-06-mellow/blob/26aa0445ec405a4ad637bddeeedec4efe1eba8d2/mellow-lrt/src/utils/DepositWrapper.sol#L30-L33
```solidity
function _ethToWsteth(uint256 amount) private returns (uint256) {
    ISteth(steth).submit{value: amount}(address(0));
    return _stethToWsteth(amount);
}
```
```solidity
function _wethToWsteth(uint256 amount) private returns (uint256) {
    IERC20(weth).safeTransferFrom(address(this), address(this), amount);
    uint256 ethAmount = IWeth(weth).withdraw(amount);
    return _ethToWsteth(ethAmount);
}
```

## Tool used

Manual Review

## Recommendation

To mitigate this issue, the `DepositWrapper` contract should handle the case where the conversion ratio between ETH and stETH (or wETH and stETH) deviates from 1:1. One possible solution is to retrieve the actual stETH balance after the conversion and use that value instead of assuming a 1:1 ratio. Here's an example of how the `_ethToWsteth()` function could be modified:

```solidity
function _ethToWsteth(uint256 amount) private returns (uint256) {
    ISteth(steth).submit{value: amount}(address(0));
    uint256 actualBalance = IERC20(steth).balanceOf(address(this));
    return _stethToWsteth(actualBalance);
}
```

Duplicate of #299

**Comment by IWildSniperI** [comment]
@z3s this is wrongly duplicated
it talkes about a different edge case about `submit` and the 1 to 1 conversion ratio
