### ISSUE TITLE
WildSniper - The `_wethToWSteth` function in the `StakingModule`  is not handling the conversion properly, leading to potential reverts. and loss of funds

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-mellow-judging#285]
WildSniper

Medium

# The `_wethToWSteth` function in the `StakingModule`  is not handling the conversion properly, leading to potential reverts. and loss of funds

## Summary
The `_wethToWSteth` function in the `StakingModule` contract is responsible for converting the `wETH` balance of the Vault to `wstETH`. However, there is an edge case that is not handled properly, leading to potential reverts.

## Vulnerability Detail
Within the `StakingModule` contract, the `_wethToWSteth` function is called by the `convert` and `convertAndDeposit` functions. The issue lies in the way the conversion from `wETH` to `wstETH` is handled, which can result in multiple reverts.

The `_wethToWSteth` function assumes a 1:1 conversion rate between the submitted `ETH` amount and the received `stETH`. However, according to the Lido documentation, in rare cases, this 1:1 ratio may not be preserved. There are two key points:

- The conversion ratio can decrease or decrease (if it decreases -> reverts) (if it increases -> permenant freeze of the extra `stETH` in `Vault`
- Although the probability is low, the impact on the end-user can be significant.

If the conversion ratio deviates from 1:1, the contract will not function correctly, preventing the conversion of `wETH` to `wstETH`. Consequently, the sortedGuardian will not be able to `depositBufferedEther`, leaving the entire contract in a non-functioning state until the conversion ratio returns to 1:1.

## Impact
High

The impact of this vulnerability is considered high, although the probability of occurrence is low. This contract is designed to convert `wETH` to `wstETH` and then `depositBufferedEther`. However, if the conversion ratio deviates from 1:1, all these operations will become non-functional.

giving the consideration of the potential loss of funds when 1 `ETH` gives more `stETH`

## Code Snippet

https://github.com/sherlock-audit/2024-06-mellow/blob/26aa0445ec405a4ad637bddeeedec4efe1eba8d2/mellow-lrt/src/modules/obol/StakingModule.sol#L77-L82

```solidity
    function _wethToWSteth(uint256 amount) private {
        IWeth(weth).withdraw(amount);
        ISteth(steth).submit{value: amount}(address(0));
        IERC20(steth).safeIncreaseAllowance(address(wsteth), amount);
        IWSteth(wsteth).wrap(amount);
    }
```

https://github.com/sherlock-audit/2024-06-mellow/blob/26aa0445ec405a4ad637bddeeedec4efe1eba8d2/mellow-lrt/src/utils/DepositWrapper.sol#L42-L75

```solidity
    function deposit(
        address to,
        address token,
        uint256 amount,
        uint256 minLpAmount,
        uint256 deadline
    ) external payable returns (uint256 lpAmount) {
        address wrapper = address(this);
        address sender = msg.sender;
        address[] memory tokens = vault.underlyingTokens();
        if (tokens.length != 1 || tokens[0] != wsteth)
            revert InvalidTokenList();
        if (amount == 0) revert InvalidAmount();
        if (token == steth) {
            IERC20(steth).safeTransferFrom(sender, wrapper, amount);
            amount = _stethToWsteth(amount);
        } else if (token == weth) {
            IERC20(weth).safeTransferFrom(sender, wrapper, amount);
            amount = _wethToWsteth(amount);
        } else if (token == address(0)) {
            if (msg.value != amount) revert InvalidAmount();
            amount = _ethToWsteth(amount);
        } else if (wsteth == token) {
            IERC20(wsteth).safeTransferFrom(sender, wrapper, amount);
        } else revert InvalidToken();

        IERC20(wsteth).safeIncreaseAllowance(address(vault), amount);
        uint256[] memory amounts = new uint256[](1);
        amounts[0] = amount;
        (, lpAmount) = vault.deposit(to, amounts, minLpAmount, deadline);
        uint256 balance = IERC20(wsteth).balanceOf(wrapper);
        if (balance > 0) IERC20(wsteth).safeTransfer(sender, balance);
        emit DepositWrapperDeposit(sender, token, amount, lpAmount, deadline);
    }
```

## Tool used

Manual Review

## Recommendation

Instead of assuming a 1:1 conversion rate, the recommended solution is to retrieve the actual `stETH` balance after the `submit` call and use that `balance` for the subsequent `safeIncreaseAllowance` and `wrap` operations. This approach ensures that the conversion is handled correctly, even in cases where the 1:1 ratio is not preserved.

Duplicate of #299

**Comment by z3s** [comment]
The protocol team comment on discord chat:
> we assume `1 steth == 1 weth`, at least for current deployments

**Comment by IWildSniperI** [comment]
@z3s 
![image](https://github.com/user-attachments/assets/84bb8493-00d6-45aa-8a30-d350a89b514d)
the comment was for chainlink oracle and not about this edge case

**Comment by IWildSniperI** [comment]
and this is not a dup of #299

**Comment by Al-Qa-qa** [comment]
Escalate.

On @IWildSniperI Behalf

**Comment by sherlock-admin3** [comment]
> Escalate.
> 
> On @IWildSniperI Behalf

You've deleted an escalation for this issue.

**Comment by z3s** [comment]
Discussion at #9
