### ISSUE TITLE
hash - DOS due to expected amount during deposits/withdrawls being lowered due to withdrawals

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-mellow-judging#288]
hash

Medium

# DOS due to expected amount during deposits/withdrawls being lowered due to withdrawals

## Vulnerability Detail
The `convertAndDeposit` and `convert` functions passes the amount to convert as a param. This `amount` of weth is supposed to be <= balance of the vault.

[link](https://github.com/sherlock-audit/2024-06-mellow/blob/26aa0445ec405a4ad637bddeeedec4efe1eba8d2/mellow-lrt/src/modules/obol/StakingModule.sol#L48-L59)
```solidity
    function convertAndDeposit(
        uint256 amount,
        uint256 blockNumber,
        bytes32 blockHash,
        bytes32 depositRoot,
        uint256 nonce,
        bytes calldata depositCalldata,
        IDepositSecurityModule.Signature[] calldata sortedGuardianSignatures
    ) external onlyDelegateCall {
        if (IERC20(weth).balanceOf(address(this)) < amount)
            revert NotEnoughWeth();

```

But the weth in the contract is movable by user actions like `emergencyWithdrawal`. Hence such a transaction will cause the `convertAndDeposit` and `convert` function calls to revert. This is especially important for `convertAndDeposit` call since it will contain the deposit related params like `guardianSigantures` etc. Such a revert will make these params public even if a private tx is used allowing other user's to manipulate the amount  

## Impact
Possible DOS on staking module deposits and withdrawals, and leakage of information allowing for users to divert the vault funds from obol validators   

## Tool used
Manual Review

## Recommendation
In `convertAndDeposit`, compute the amount rather passing the predefined amount and limit the amount to vault's balance incase of `convert`

**Comment by 10xhash** [comment]
> > DoS has two separate scores on which it can become an issue:
> > 
> > 1. The issue causes locking of funds for users for more than a week.
> > 2. The issue impacts the availability of time-sensitive functions
> 
> `convertAndDeposit` can be used with high gas or with flashbots to mitigate this problem.

Escalate

The `convert` function gets invoked inside the `processWithdrawals` call and this function too would have to be assumed to be using private transactions (both these are not mentioned to be doing so)
When there are pending `emergencyWithdrawals` this problem can happen under natural operation of the protocol and doesn't require a malicious front run (low likelihood though since it requires pending `emergencyWithdrawals` and those tx's to happen before this tx)

This part of the report is incorrect `Such a revert will make these params public even if a private tx is used` because it has happened as a bug that reverting private txs were published but normally such txs would not be published

**Comment by sherlock-admin3** [comment]
> > > DoS has two separate scores on which it can become an issue:
> > > 
> > > 1. The issue causes locking of funds for users for more than a week.
> > > 2. The issue impacts the availability of time-sensitive functions
> > 
> > `convertAndDeposit` can be used with high gas or with flashbots to mitigate this problem.
> 
> Escalate
> 
> The `convert` function gets invoked inside the `processWithdrawals` call and this function too would have to be assumed to be using private transactions (both these are not mentioned to be doing so)
> When there are pending `emergencyWithdrawals` this problem can happen under natural operation of the protocol and doesn't require a malicious front run (low likelihood though since it requires pending `emergencyWithdrawals` and those tx's to happen before this tx)
> 
> This part of the report is incorrect `Such a revert will make these params public even if a private tx is used` because it has happened as a bug that reverting private txs were published but normally such txs would not be published     

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
> This part of the report is incorrect Such a revert will make these params public even if a private tx is used because it has happened as a bug that reverting private txs were published but normally such txs would not be published

Since this part of the report is incorrect, then the only impact is DOS, how long can this DOS occur? And could you send a link to the `processWithdrawals`, cause I see one [here](https://github.com/sherlock-audit/2024-06-mellow/blob/26aa0445ec405a4ad637bddeeedec4efe1eba8d2/mellow-lrt/src/Vault.sol#L536) but it doesn't call the `convert` function?

**Comment by 10xhash** [comment]
> > This part of the report is incorrect Such a revert will make these params public even if a private tx is used because it has happened as a bug that reverting private txs were published but normally such txs would not be published
> 
> Since this part of the report is incorrect, then the only impact is DOS, how long can this DOS occur? And could you send a link to the `processWithdrawals`, cause I see one [here](https://github.com/sherlock-audit/2024-06-mellow/blob/26aa0445ec405a4ad637bddeeedec4efe1eba8d2/mellow-lrt/src/Vault.sol#L536) but it doesn't call the `convert` function?

https://github.com/sherlock-audit/2024-06-mellow/blob/26aa0445ec405a4ad637bddeeedec4efe1eba8d2/mellow-lrt/src/strategies/SimpleDVTStakingStrategy.sol#L62-L84
```solidity
    function processWithdrawals(
        address[] memory users,
        uint256 amountForStake
    ) external returns (bool[] memory statuses) {
        _requireAtLeastOperator();
        if (users.length == 0) return statuses;
        emit ProcessWithdrawals(users, amountForStake, msg.sender);


        if (amountForStake == 0) return vault.processWithdrawals(users);


        vault.delegateCall(
            address(stakingModule),
            abi.encodeWithSelector(
                IStakingModule.convert.selector,
                amountForStake
            )
        );


        statuses = vault.processWithdrawals(users);
        address wsteth = stakingModule.wsteth();
        uint256 balance = IERC20(wsteth).balanceOf(address(vault));
        if (balance > maxAllowedRemainder) revert LimitOverflow();
    }
```

DOS is not a sustaining one. If there are emergencyWithdrawals done by user's in a block then the `processWithdrawals` call in the same block could revert

**Comment by WangSecurity** [comment]
Thank you very much for clarification. In that case I believe it doesn't qualify for DOS requirements (funds are not locked for  7 days and `processWithdrawals` I believe is not time sensitive) and should remain invalid. 

Planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [10xhash](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/288/#issuecomment-2231738039): rejected
