### ISSUE TITLE
hals - `ChainlinkOracle._validateAndGetPrice()` doesn't correctly validate the returned price

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-mellow-judging#300]
hals

Medium

# `ChainlinkOracle._validateAndGetPrice()` doesn't correctly validate the returned price

## Summary

`ChainlinkOracle._validateAndGetPrice()` doesn't correctly validate the returned price as it allows the returned price to be zero or out of an acceptable price range (irreasonable price validation).

## Vulnerability Detail

- `ChainlinkOracle._validateAndGetPrice()` function is invoked whenever `getPrice()` is invoked to fetch the latest price for a specific token from the given vault's associated Chainlink oracle:

```js

    function _validateAndGetPrice(
        AggregatorData memory data
    ) private view returns (uint256 answer, uint8 decimals) {

        if (data.aggregatorV3 == address(0)) revert AddressZero();

        (, int256 signedAnswer, , uint256 lastTimestamp, ) = IAggregatorV3(
            data.aggregatorV3
        ).latestRoundData();
        // The roundId and latestRound are not used in the validation process to ensure compatibility
        // with various custom aggregator implementations that may handle these parameters differently
        if (signedAnswer < 0) revert InvalidOracleData();
        answer = uint256(signedAnswer);
        if (block.timestamp - data.maxAge > lastTimestamp) revert StaleOracle();
        decimals = IAggregatorV3(data.aggregatorV3).decimals();
    }
```

where the fetched priced is checked for staleness (`block.timestamp - data.maxAge > lastTimestamp`) and if its's `signedAnswer < 0`.

- But this doesn't correctly validate that the fetched price:

1. The `IAggregatorV3(data.aggregatorV3).latestRoundData()` could return a zero price if no answer has been reached.
2. The returned price could be out of an acceptable range, as there's no `minAnswer/maxAnswer` circuit breaker checks on the returned price, and this could be as a result of a huge drop/pump of the asset value where the oracle will continue returning the minAnswer/maxAnswer instead of the actual market price of the asset.

## Impact

This would result in using incorrect assets prices fetched by the `ChainlinkOracle.priceX96()`, where this function is invoked by the `Vault` to evaluate the total value locked, thus resulting in incorrect shares being minted to the users (lp tokens) and incorrect values redeemed (withdrawn) by the users.

## Code Snippet

https://github.com/sherlock-audit/2024-06-mellow/blob/26aa0445ec405a4ad637bddeeedec4efe1eba8d2/mellow-lrt/src/oracles/ChainlinkOracle.sol#L56C5-L69C6

## Tool used

Manual Review

## Recommendation

Update `ChainlinkOracle._validateAndGetPrice()` to check against zero price if returned, and to validate the fetched price is within a an acceptable range (add `minPrice` & `maxPrice` to the `_aggregatorsData[vault][token]`).

**Comment by InfectedIsm** [comment]
Escalate

This is a common practice to check price against zero. 
Why would you check against value `< 0` but exclude 0 ? 
I don't think such an error would be less impactful than a price `< 0` 

Also, this ~~should~~ shouldn't be duplicated with issue checking min/maxAnswer

edit: fixed typo

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This is a common practice to check price against zero. 
> Why would you check against value `< 0` but exclude 0 ? 
> I don't think such an error would be less impactful than a price `< 0` 
> 
> Also, this should be duplicated with issue checking min/maxAnswer

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by tpiliposian** [comment]
> Escalate
> 
> This is a common practice to check price against zero. Why would you check against value `< 0` but exclude 0 ? I don't think such an error would be less impactful than a price `< 0`
> 
> Also, this should be duplicated with issue checking min/maxAnswer

I definitely agree. Why is it that in some places, non-correspondence with documentation is considered a valid medium severity issue, but now, when it doesn't correspond with Chainlink docs, it's not? This implementation is not a fully correct check, as zero prices may indicate stale or malicious data.

**Comment by WangSecurity** [comment]
> Why is it that in some places, non-correspondence with documentation is considered a valid medium severity issue, but now, when it doesn't correspond with Chainlink docs, it's not?

In such cases medium severity is assigned only if the issue breaks the statement in the README, not in the documentation.

Secondly, could someone send a link to the following part of the code 
> Vault to evaluate the total value locked, thus resulting in incorrect shares being minted to the users (lp tokens) and incorrect values redeemed (withdrawn) by the users

**Comment by InfectedIsm** [comment]
> Secondly, could someone send a link to the following part of the code
> 
> > Vault to evaluate the total value locked, thus resulting in incorrect shares being minted to the users (lp tokens) and incorrect values redeemed (withdrawn) by the users

@WangSecurity you can find how lp tokens are calculated here in [Vault::deposit`](https://github.com/sherlock-audit/2024-06-mellow/blob/26aa0445ec405a4ad637bddeeedec4efe1eba8d2/mellow-lrt/src/Vault.sol#L285-L338)
1. `L305`:  `totalAmounts` are read
2. `L321` price oracle is read
3. `L322-335` `totalValue` and `depositValue` are computed 
4. `L338` LP amount to mint is computed with `totalValue` and `depositValue` 

Similar logic in `Vault::processWithdrawals`
We must not forget that vaults can have more than 1 underlying token.

**Comment by 10xhash** [comment]
> > Why is it that in some places, non-correspondence with documentation is considered a valid medium severity issue, but now, when it doesn't correspond with Chainlink docs, it's not?
> 
> In such cases medium severity is assigned only if the issue breaks the statement in the README, not in the documentation.
> 
> Secondly, could someone send a link to the following part of the code
> 
> > Vault to evaluate the total value locked, thus resulting in incorrect shares being minted to the users (lp tokens) and incorrect values redeemed (withdrawn) by the users

Chainlink oracles usually limit the price range allowed to be reported from 1 to type(int176.max). This check will disallow 0 being reported as the price

https://github.com/smartcontractkit/libocr/blob/ae747ca5b81236ffdbf1714318c652e923a5ff4d/contract/OffchainAggregator.sol#L681-L685

Since usually the latestRoundId is only updated along with the answer (which will also have to pass the above check) I think the below statement is false except for round0

https://github.com/smartcontractkit/libocr/blob/ae747ca5b81236ffdbf1714318c652e923a5ff4d/contract/OffchainAggregator.sol#L682-L709

`The IAggregatorV3(data.aggregatorV3).latestRoundData() could return a zero price if no answer has been reached`

Else if there is any specific oracle that is involved with the protocol that deviates from this general behavior I think it should be explicitly mentioned to consider this viable

**Comment by WangSecurity** [comment]
Firstly, Chainlink Oracle in this case is a trusted admin which we have to assume will return correct data.
Secondly, if the oracle returns 0, then as I understand, deposit value and total value will be both 0, then when the deposit calls `processLpAmount` it will revert at [L360-361](https://github.com/sherlock-audit/2024-06-mellow/blob/26aa0445ec405a4ad637bddeeedec4efe1eba8d2/mellow-lrt/src/Vault.sol#L360C1-L362C1) because it will not pass slippage. While the slippage is user input amount and if they input 0 resulting in a 0 lp tokens minted, I'm afraid it's their mistake. 
Thirdly, as far as I'm aware, chanlink's oracles have never returned 0 price for any asset.

I believe the issue is low/info severity. Planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [InfectedIsm](https://github.com/sherlock-audit/2024-06-mellow-judging/issues/300/#issuecomment-2232373617): rejected
