### ISSUE TITLE
tedox - `Vault::deposit()` doesn't account for tokens with different decimals

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-mellow-judging#60]
tedox

High

# `Vault::deposit()` doesn't account for tokens with different decimals

## Summary

When depositing in `Vault::deposit()` you are required to deposit tokens in a specific  ratio specified by the contract. This ratio does not account for the fact that some of the underlying tokens have different amount of decimals which can result in incorrect calculations of LP tokens to mint and how much the user is supposed to pay for them.

## Vulnerability Detail

When calling `Vault::deposit()` the function uses the following formulas to ensure the correct ratio of assets (for the current example we are going to use only 2 underlying assets (WETH, USDC) in ratio 3:1 respectively

 ```solidity
 ratioX96 = inf 
 ratioX96 = min(ratioX96, amountUSDC * 2^96 / (2^96 / 4)) 
 ratioX96 = min(ratioX96, amountWETH * 2^96 / (2^96 * 3 / 4)) 
```

Now if we plug in values for `amountUSDC = 10*10^6` (USDC uses 6 decimals) and `amountWETH = 30*10^18` (WETH uses 18 decimals. The calculation results in

 ```solidity
 ratioX96 = inf
 ratioX96 = min(inf, 10*10^6 * 2^96 / (2^96 / 4))   //ratioX96 = 40*10^6
 ratioX96 = min(40*10^6, 30*10^18 * 2^96 / (2^96 * 3 / 4))   //ratioX96 = min(40*10^6, 26*10^18), ratioX96= 40*10^6
```

Then continuing the calculation for `actualAmounts`

```solidity
        for (uint256 i = 0; i < tokens.length; i++) {
            uint256 priceX96 = priceOracle.priceX96(address(this), tokens[i]);
            totalValue += totalAmounts[i] == 0
                ? 0
                : FullMath.mulDivRoundingUp(totalAmounts[i], priceX96, Q96);
            if (ratiosX96[i] == 0) continue;
@>          uint256 amount = FullMath.mulDiv(ratioX96, ratiosX96[i], Q96);
            IERC20(tokens[i]).safeTransferFrom(
                msg.sender,
                address(this),
                amount
            );
@>         actualAmounts[i] = amount;
            depositValue += FullMath.mulDiv(amount, priceX96, Q96);
        }
```

Using the values we got 

```solidity
actualAmounts[USDC] = (40*10^6) * (2^96 / 4) / 2^96 // amounts[USDC] = 10*10^6
actualAmounts[WETH] = (40*10^6) * (2^96 * 3 / 4) / 2^96 // amounts[WETH] = 30*10^6
```

Now the expected amount of tokens would be `30ETH = 30*10^18` and `10USDC = 10*10^6` which is the required 3:1 ratio but we actually got `10^(-12)ETH = 30*10^6` instead. Because of that the contract is going to think it has 30ETH but it would have actually received a negligible amount of ETH and is going to mint more LP tokens than the user has actually paid for because the amount received is not what the user has specified in `amounts[]` but what is calculated as `actualAmounts`

## Impact

All of the calculations inside the contract are going to be wrong because `depositValue` is not going to be a realistic representation of `actualAmounts`

## Code Snippet

https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L310-L336

## Tool used

Manual Review

## Recommendation

Ensure that either the ratios account for the differences in decimals or change the calculations inside `Vault::deposit()` to account for different amounts of decimals

Duplicate of #160

**Comment by z3s** [comment]
From known issues:
> In src/oracles/ChainlinkOracle.sol, the priceX96 function does not take into account IERC20(base).decimals() and IERC20(token).decimals() when converting. For the current deployment, this is not a problem because the system operates with tokens from the set [weth, wsteth, steth].
