### ISSUE TITLE
Audinarey - `processWithdrawals(...)` will revert if an underlying token is added when there are pending requested withdrawals

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-mellow-judging#83]
Audinarey

Medium

# `processWithdrawals(...)` will revert if an underlying token is added when there are pending requested withdrawals

## Summary
The `Vault::processWithdrawals(...)` function is called by the an authorised account to Processes multiple withdrawal requests by fulfilling eligible withdrawals for multiple withdrawers. 

```solidity
    /// @inheritdoc IVault
    function processWithdrawals(
        address[] memory users
    ) external nonReentrant returns (bool[] memory statuses) {
        _requireAtLeastOperator();
        statuses = new bool[](users.length);
 @>     ProcessWithdrawalsStack memory s = calculateStack();
        uint256 burningSupply = 0;
        for (uint256 i = 0; i < users.length; i++) {
           ......

            (
                bool isProcessingPossible,
                bool isWithdrawalPossible,
                uint256[] memory expectedAmounts
 @>         ) = analyzeRequest(s, request);

```
 
`processWithdrawals(...)` calls the `calculateStack()` function to evaluate the current state stack required for processing withdrawal requests as shown below

```solidity
    function calculateStack()
        public
        view
        returns (ProcessWithdrawalsStack memory s)
    {
        (address[] memory tokens, uint256[] memory amounts) = underlyingTvl();
        s = ProcessWithdrawalsStack({
            tokens: tokens,
            ratiosX96: IRatiosOracle(configurator.ratiosOracle())
                .getTargetRatiosX96(address(this), false),
  @>        erc20Balances: new uint256[](tokens.length),
           ...
  @>        tokensHash: keccak256(abi.encode(tokens))
        });

        IPriceOracle priceOracle = IPriceOracle(configurator.priceOracle());
@>      for (uint256 i = 0; i < tokens.length; i++) {
            uint256 priceX96 = priceOracle.priceX96(address(this), tokens[i]);
            s.totalValue += FullMath.mulDiv(amounts[i], priceX96, Q96);
@>          s.ratiosX96Value += FullMath.mulDiv(s.ratiosX96[i], priceX96, Q96);
@>          s.erc20Balances[i] = IERC20(tokens[i]).balanceOf(address(this));
        }
    }
```
notice that `calculateStack()` 
- evaluates  the `erc20Balances` based on the length of the current underlying tokens array
- sets a the `tokensHash` based on the the current underlying tokens array in the vault (and if this array changes then `tokensHash` also changes whenever an underlyiing token is added or removed

`processWithdrawals(...)` also calls the `analyzeRequest()` to analyse `each` user's withdrawal request based on the current vault state as shown below

```solidity
File: Vault.sol
478:     function analyzeRequest(
479:         ProcessWithdrawalsStack memory s,
480:         WithdrawalRequest memory request
481:     ) public pure returns (bool, bool, uint256[] memory expectedAmounts) { // processingPossible, withdrawalPossible, expectedAmounts
482:         uint256 lpAmount = request.lpAmount;
483:         if ( 
484: @>          request.tokensHash != s.tokensHash || request.deadline < s.timestamp
485:         ) return (false, false, expectedAmounts); 
486: 
...
490: 
491: @>      uint256 length = s.erc20Balances.length;
492: @>      expectedAmounts = new uint256[](length);
493: @>      for (uint256 i = 0; i < length; i++) {
...
498: @>           if (expectedAmounts[i] >= request.minAmounts[i]) continue;
499:             return (false, false, expectedAmounts); 
500:         }
....
505:         return (true, true, expectedAmounts);
506:     }

```
notice that `analyzeRequest()` 
- on `L484` compares the `request.tokensHash` which is cached at the time the users made the  withdrawal request and the `s.tokensHash` evaluated at the point of processing the withdrawal in `calculateStack()`  above. (`request.tokensHash != s.tokensHash`).
- caches `s.erc20Balances.length` on `L491` which is the current length of underlying token balances and uses this length on `L498` to check if the `expectedAmounts[i]` is enough to settle each specified `request.minAmounts[i]` of the request under consideration. 

Lastly the `registerWithdrawal(...)` is used to Registers a new withdrawal request and as shown below,

```solidity
File: Vault.sol
435:     /// @inheritdoc IVault
436:     function registerWithdrawal(
437:         address to,
438:         uint256 lpAmount,
439:         uint256[] memory minAmounts,
440:         uint256 deadline,
441:         uint256 requestDeadline,
442:         bool closePrevious
443:     )
.......
448:     {
.......
459: 
460:@>       address[] memory tokens = _underlyingTokens;
461:@>       if (tokens.length != minAmounts.length) revert InvalidLength();
462: 
463:         WithdrawalRequest memory request = WithdrawalRequest({
464:             to: to,
465:             lpAmount: lpAmount,
466:@>           tokensHash: keccak256(abi.encode(tokens)),
467:             minAmounts: minAmounts,
468:             deadline: requestDeadline,
469:             timestamp: timestamp
470:         });
........
475:     }

```
notice that
- the `tokensHash` of the withdrawal request at the point the withdrawal is requested is cached on `L466` based on the current underlying tokens in the vault
- the `minAmounts` array length must be equal to the length of the current `_underlyingTokens` at the point of requesting the withdrawal 

## Vulnerability Detail

**The problem is that**, if an underlying token is added between the time when the user calls `registerWithdrawal(...)` to register his withdrawal and when `processWithdrawals(...)` is called by an operator, then `processWithdrawals(...)`  will cancel the user's withdrawal because 
- the `tokensHash` is changed when an underlying token is added and as such the block below will return
    - `processingPossible` == false
    - `withdrawalPossible` == false
```solidity
File: Vault.sol
483:         if ( 
484: @>          request.tokensHash != s.tokensHash || request.deadline < s.timestamp
485:         ) return (false, false, expectedAmounts);  // // processingPossible, withdrawalPossible, expectedAmounts
```
Also worthy of mention is that

- Alice request withdrawal when there are 3 underlying tokens
- admin adds new underlying token making it 4 underlying tokens
- admin calls `processWithdrawals(...)` but the request is cancelled and she has to request and wait again or even use emergency withdraw at a loss
```solidity
File: Vault.sol
555:             if (!isProcessingPossible) {
556:                 _cancelWithdrawalRequest(user); // @audit of course the request will be cancelled, but the withdrawal time will be extended
557:                 continue;
558:             }

```
Another reason why `processWithdrawals(...)` will not work for a user's request is that as seen in the code block below, `expectedAmounts.length` will be greater than `request.minAmounts.length` leading to an _array out of bound_ scenario hence causing a revert for `processWithdrawals(...)` function

```solidity
498: @>           if (expectedAmounts[i] >= request.minAmounts[i]) continue;
```

## Impact
Withdrawals will be cancelled  and  `processWithdrawals(...)` function will possibly revert when called causing a Denial of service in the vault withdrawals.

## Code Snippet
https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L536-L552

https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L512-L517

https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L482-L501

https://github.com/sherlock-audit/2024-06-mellow/blob/main/mellow-lrt/src/Vault.sol#L459-L464

## Tool used
- Foundry test
- Manual Review

## Recommendation
Prevent adding a token when there are pending withdrawals, hence modify the `addToken(...)` function as shown below

```solidity
File: Vault.sol
184:     function addToken(address token) external nonReentrant { 
185:         _requireAdmin();
186:         if (token == address(0)) revert InvalidToken();
187:         if (_isUnderlyingToken[token]) revert InvalidToken();
188:         if (token == address(this)) revert InvalidToken();
189:         _isUnderlyingToken[token] = true;
190:         address[] storage tokens = _underlyingTokens; 
191:  +      require(_pendingWithdrawers.length() == 0, "existingPendingWithdrawals());
.....
202:         tokens[index] = token;
203:         emit TokenAdded(token);
204:     }

```

**Comment by Audinarey** [comment]
@z3s @WangSecurity 

During withdrawal registration  the token hash of the vaults current state is hashed as seen on L466.
However, the `addToken(...)` function changes the `tokensHash` of the `ProcessWithdrawalsStack` and as such  if `addToken(...)` is called between the time a withdrawalRequest was queued and when `processWithdrawals(...)` is called for the request, the WithdrawalRequest   will be cancelled.

This is because `request.tokensHash != s.tokensHash` thus the ` processingPossible` and `withdrawalPossible` will return false causing the withdrawal to be cancelled on L556

```solidity
436:     function registerWithdrawal(
437:         address to,
438:         uint256 lpAmount,
439:         uint256[] memory minAmounts,
440:         uint256 deadline,
441:         uint256 requestDeadline,
442:         bool closePrevious
443:     )
.......
448:     {
.......
459: 
460:@>       address[] memory tokens = _underlyingTokens;
461:@>       if (tokens.length != minAmounts.length) revert InvalidLength();
462: 
463:         WithdrawalRequest memory request = WithdrawalRequest({
464:             to: to,
465:             lpAmount: lpAmount,
466:@>           tokensHash: keccak256(abi.encode(tokens)),
467:             minAmounts: minAmounts,
468:             deadline: requestDeadline,
469:             timestamp: timestamp
470:         });

........
475:     }
483:         if ( 
484: @>          request.tokensHash != s.tokensHash || request.deadline < s.timestamp
485:         ) return (false, false, expectedAmounts);turn (false, false, expectedAmounts); // processingPossible, withdrawalPossible, expectedAmounts
 ......

555:             if (!isProcessingPossible) {
556:  @>             _cancelWithdrawalRequest(user); // @audit of course the request will be cancelled, forcing the user to queue the request again
557:                 continue;
558:             }
```

To put in context<
- Alice request withdrawal when there are 3 underlying tokens when `request.tokensHas == s.tokensHash` == abc
- admin adds new underlying token making it 4 underlying tokens `s.tokensHash` == abcd
- admin calls processWithdrawals(...) but the request is cancelled because `abc` != `abcd` and she has to request and wait again or even use emergency withdraw at a loss


Please pardon the title of the finding

**Comment by z3s** [comment]
Both of these are admin function, so we can assume they will handle withdrawals before adding new tokens.

**Comment by Audinarey** [comment]
@z3s 

> Both of these are admin function, so we can assume they will handle withdrawals before adding new tokens.

- As SRs, we cannot safely assume admin will handle withdrawals before adding new tokens (in this context) because if that were the case, a malicious actor can keep on registering withdrawals to ensure that there is always a withdrawal request in the Vault.
This in itself opens up a path for a DOS to prevent adding and removing tokens

- Also the `removeToken(...)` function has the same effect as add token would if called in the same sequence that is described in this finding i.e
    - `registerWithdrawal(...)` -> `addToken(...)` -> `processWithdrawals(...)`
    - `registerWithdrawal(...)` -> `removeToken(...)` -> `processWithdrawals(...)`

- Also considering that the tokens used are external to the protocol, external factors in any of those tokens cause admin to remove and/or replace (add) a token.


Thus I believe is a valid medium
